nodegit/nodegit

- generate/combyne/partials/async_function.cc
Continuing from https://github.com/nodegit/nodegit/issues/331, as it is a different issue.
Here is the backtrace obtained via lldb:
```
* thread #1: tid = 0xdd2c0, 0x00007fff973f219f libsystem_malloc.dylib`malloc_error_break, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
* frame #0: 0x00007fff973f219f libsystem_malloc.dylib`malloc_error_break
frame #1: 0x00007fff973e38c5 libsystem_malloc.dylib`free + 314
frame #2: 0x000000010327f77b nodegit.node`GitCommit::LookupWorker::HandleOKCallback(this=0x0000000100d09790) + 859 at commit.cc:689
frame #3: 0x000000010324d812 nodegit.node`NanAsyncWorker::WorkComplete(this=0x0000000100d09790) + 66 at nan.h:1881
frame #4: 0x000000010324e2d1 nodegit.node`NanAsyncExecuteComplete(req=0x0000000100d09798) + 33 at nan.h:1948
frame #5: …
```
> Do not double free during callbacks.

- package.json
Looks like nodegit works fine with fs-extra v0.14, would you like to merge this PR, thanks.
> Update dependency fs-extra to ~0.14.0

- generate/input/descriptor.json
- test/tests/checkout.js
This exposes the libgit2 `git_checkout_head` method and adds a test. This method will let the user put whatever is in the index that's pointed to by HEAD into the passed repository.
> Added checkout head method and tests

- lib/commit.js
- test/tests/commit.js
getParents failed when more than one commit was present, since it attempted
to get the second parent of commit's parent instead of it's own second
parent.
The promise for the second parent was also pushed onto the array for
Promise.all() too late to actually have an effect.
Limit was not working properly as a limit, since it attempted to
retrieve the set limit regardless of how many parents a commit had,
failing if the limit was set to more than Commit.parentcount().
> Commit.getParents working with merge commits

- .gitignore
- generate/input/descriptor.json
- lib/commit.js
- test/tests/diff.js
Also, update Commit.getDiff to diff when no parents exists eg. the initial commit of a repository.
> Allow null trees on Diff.treeToTree

- .travis.yml
Doesn't make sense to just remove on Windows.  Lets just drop 0.11 completely for now.
> Removes Node 0.11 testing completely

- examples/cloneFromGithubWith2Factor.js
- generate/input/descriptor.json
- test/tests/cred.js
This was causing weird segfault issues, no idea why any of them were this way (rather, why we didn't override them when we noticed they were async). Also added an example of 2factor auth.
https://github.com/nodegit/nodegit/pull/375
https://github.com/nodegit/nodegit/issues/323
https://github.com/nodegit/nodegit/issues/321
> Make all cred generators sync.

- lib/revwalk.js
- test/tests/revwalk.js
Adds getCommits() which takes in a number (or defaults to 10) and grabs that many commits from the walker. 
Also adds getCommitsUntil which takes in a check function, and grabs commits until the function returns false called against a commit;
> Add 2 convenience methods to revwalk

- lifecycleScripts/install.js
- lifecycleScripts/retrieveExternalDependencies.js
Building nodegit was breaking if a space was anywhere in the path because `child_process.exec` treats spaces as a delimiter. See http://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback.
> Fix building when a space is in the path

- generate/input/libgit2-supplement.json
- generate/templates/partials/field_accessors.cc
- generate/templates/templates/struct_content.cc
- test/tests/diff.js
libgit2 provides `diff_options` flags to `git_diff_tree_to_workdir_with_index` such as including untracked (unstaged) files in a diff. I've added that here using the `normalizeOptions` pattern and it does not seem to be working. I think being able to pass these flags in increases nodegit's usefulness to a wider range of use cases, so I'd like to get this working here.
> INCLUDE_UNTRACKED option not working for diffs

- generate/scripts/generateJson.js
- generate/scripts/helpers.js
- package.json
- test/tests/commit.js
Updates the lodash version. As of 3.0.0, lodash chainable foreach is lazy, and you have to call .value() at the end of the chain for it to evaluate.
> Update moar dependencies.

- package.json
We need to expose garbage collection for all revwalk tests to run, this brings us to 113 passing assertions
> Expose gc so all tests run in CI

- lib/tree_entry.js
- test/tests/tree_entry.js
While moving code from the older v0.1.x codebase to the latest, I tried making minimal changes and renames in some functions. A majority of my Node code at this time is not using promises. While calling `getBlob(callback)` on a tree_entry, nothing happened.
I simply mimicked the format used for `getTree` in tree_entry to be consistent (although I'm not setting the `entry` instance on a property like the tree function does).
> Tree Entry getBlob() should also support the callback pattern.

- generate/input/descriptor.json
- generate/templates/partials/sync_function.cc
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
Some properties were being set on the libgit2 C struct but would
be destroyed after the function is completed. The problem was that
C struct would still assume that the memory it had was valid and
would try to use it resulting in random segfaults.
Now you can mark an argument as `saveArg` and then that argument
will be persisted to the parent object and disposed of when the
parent is deleted.
Currently this only works in sync functions since I couldn't find
an async method that would need this. If this changes it shouldn't
be too hard to implement.
Another thing to note is that the if the parent object is marked
as `!selfFreeing` then we're still going to dispose of the
persisted objects because if not then they will memory leak all
over the place. This might need to be looked into more …
> Allow for saving of props to an object

- test/tests/remote.js
Currently the transfer progress test is breaking on windows
randomly. @tbranyen and I have been looking into it and it seems
like a libuv issue. I'm going to skip this now so that other
potential PR's aren't held up by it until we can get a good
resolution and fix it in another PR
> Skip transfer progress test until it's fixed

- lib/clone.js
- test/runner.js
- test/tests/clone.js
Once a repository has been successfully cloned, free the internal
structure to avoid file locking.  Then open the repository again to
providea repository opbject.
> Automatically free repositories post clone

- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/struct_header.h
- test/tests/remote.js
`uv_queue_work` is [not thread safe]
(http://docs.libuv.org/en/v1.x/threadpool.html)
This means that all callbacks are in a highly unstable
state and can bring the system down at any time.
Now we're using an [Async handle]
(http://docs.libuv.org/en/latest/async.html#c.uv_async_t)
That should make out callbacks thread safe and consistent
across platforms again
> Fix libuv threading issue

- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
- generate/templates/partials/fields.cc
- lib/repository.js
- lib/status_file.js
- lib/status_list.js
- test/tests/repository.js
- test/tests/status_file.js
- test/tests/status_list.js
> Status.byIndex and StatusEntry

- lib/repository.js
- test/tests/signature.js
If the user name or email wasn't set then `repo.defaultSignature`
would return an invalid signature that couldn't be used in other
operations. Now the method will return a signature of an "unknown"
user that can be used anywhere.
This fixes #431
> Default signature always returns valid signature

- generate/templates/manual/src/str_array_converter.cc
This fixes up the conversion of string arrays. The problem is that the `ConvertArray` function was setting the string pointer to the internals of `NanUtf8String` but the class was being destroyed freeing the memory.
I also removed the need to call `ConstructStrArray` as that just does more string duplications (`strdup`) that aren't really needed.
The commits on this branch provide a clean transistion between the two methods that are more obvious that the complete branch diff.
> Str array converter fix

- generate/input/descriptor.json
- lib/diff.js
- test/tests/diff.js
Also DiffFindOptions.
This allows a diff of additions and deletions to be rewritten as renames, or to split a heavily modified file into separate file deletions and additions rather than one modification.
> Add Diff.prototype.findSimilar

- test/tests/clone.js
I set up an HTTP backend for my Git repositories.  We can use this for now, but I'd like to have a standalone with GitHub or Bitbucket..  Relying on this URL long-term seems like a bad idea.
> Added in an HTTP url for test

- examples/clone.js
- examples/cloneFromGithubWith2Factor.js
- lib/clone.js
- test/tests/clone.js
Right now we have the current call mechanism for clone:
``` javascript
var Git = require('nodegit');
Git.Clone.clone('https://github.com/nodegit/nodegit', 'nodegit').then(function(repo) {
/* work with the repository */
});
```
This is pretty verbose, compared to:
``` javascript
var Git = require('nodegit');
Git.Clone('https://github.com/nodegit/nodegit', 'nodegit').then(function(repo) {
/* work with the repository */
});
```
So I've fixed that in the JS-side.  The top-level `NodeGit.Clone` Object is now a Function that behaves like an Object.
This is not a backwards-breaking change, so hopefully we're all in favor?
> Better cloning with NodeGit

- generate/templates/manual/include/str_array_converter.h
- generate/templates/manual/src/str_array_converter.cc
We were only allocating enough memory for a `git_strarray` memory pointer rather than the structure.  1a74a2d fixes that.
7c81612 changes the code to allocate the memory for the structure and the string pointers all in one go to reduce fragmentation. Complete micro-optimisation, happy for it to not get merged but thought I'd do it anyway.
> StrArray memory fix

- generate/templates/templates/enums.js
This fixes callstack errors with `apm`. I think the __proto__ assignment is a recent thing, maybe added by @maxkorp? Tests pass without, so not sure the reason for the addition.
What think ye?
> Don't assign enums to __proto__

- lib/repository.js
- test/runner.js
- test/tests/checkout.js
A very common thing to do in git is to checkout a new branch.
Instead of having to manually do both steps this convenience
function will now combine both into 1 command. Also added a test
for the new method.
> Add checkoutBranch convenience method

- generate/input/descriptor.json
- lib/repository.js
Changes the descriptor file to convert setHead to be asynchronous and
return an error code. Also modifies the createBranch method to
waterfall promises from setHead into Checkout.head.
> Change Repository.prototype.setHead to be asynchronous

- lib/repository.js
The convenience method `createCommitOnHead` was adding files being
ignored via `.gitignore` which is really bad. Now it's changed to
use the `Index.prototype.addAll` method since it's available now
and it wasn't when that method was written.
> Fix `createCommitOnHead`

- lib/remote.js
Instead of forcing the user to pass in a signature and message
each time they call push we can derive a good default for them.
> Add defaults to `Remote.prototype.push`

- lib/repository.js
Since pruning a remote is very common after a fetch I figured
having it be an option would be very convenient for the user.
> Add option to `fetch` to prune the remote afterwards

- README.md
The link to the API documentation isn't clickable on NPM - apparently it needs to be explicitly marked up as a link!
> Updated API documentation link to work with NPM's markdown renderer. 

- lifecycleScripts/install.js
The home directory wasn't being set correctly for atom-shell
install in a windows environment. Now things should work again.
> Fix atom-shell install on windows

- generate/input/descriptor.json
- lib/index.js
- test/tests/pathspec.js
See here: https://github.com/libgit2/libgit2/issues/2687
Doing this speeds things up from around 2500-3500ms for a small-medium repo to around 180-200ms. We should remove this once it's fixed in libgit2, but until then, this seems silly not to add. 
This also adds pathspec.create (since we need that to actually compare pathspecs)
> Make index.addAll use status to increase performance

- lifecycleScripts/install.js
When installing on atom-shell in windows it would add a trailing
space to the .atom-shell-gyp directory. Removing that directory is
a pain since windows doesn't handle trailing spaces too well.
This is an attempt to fix that.
> Fix trailing space in atom-shell windows install

- lifecycleScripts/install.js
When not using Node 0.10.x we would sometimes have a missing
builder (i.e. pangyp or nw-gyp). We'll now do an `npm install` for
whatever builder we're using to make sure it exists.
> Confirm builder exists before building

- lifecycleScripts/install.js
Some dev dependencies were slipping through the cracks during an
atom-shell or nw.js install. For now we'll just download all
dev dependencies before a build just in case.
> Download all dev dependencies before build

- README.md
This newline is breaking the link for the gitter badge on npm.
> Fix gitter badge for npm

- examples/general.js
- lib/repository.js
I also updated the example in `general.js` so that it would return symbolic references as expected.
> Fix symbolic reference handling in getReferences

- guides/cloning/README.md
- guides/cloning/gh-two-factor/README.md
- guides/cloning/ssh-with-agent/README.md
- guides/install/README.md
- guides/install/atom-shell/README.md
- guides/install/from-source/README.md
- guides/install/nw.js/README.md
- guides/repositories/initializing/README.md
When you click on install basics you get a return to install guides, but
that is actually the root guides.  If you click on install atom shell
and return to install guides it actually brings you back to install
basics.  This is super confusing, I've updated it so that every section
returns to the main list.
> Guide navigation is currently confusing

- guides/cloning/README.md
- guides/cloning/gh-two-factor/README.md
- guides/cloning/ssh-with-agent/README.md
- guides/install/README.md
- guides/install/atom-shell/README.md
- guides/install/from-source/README.md
- guides/install/nw.js/README.md
- guides/repositories/README.md
- guides/repositories/initializing/README.md
Fixes nodegit/nodegit#494
Not sure what happened, but it doesn't look like the documentation changes made it into `master`?
- Add fixes from nodegit/nodegit@2fe55cc.
- Fix basic install links at the top of the guide pages.
> Revert "Guide navigation is currently confusing"

- generate/templates/manual/src/functions/copy.cc
- package.json
This removes files that we didn't author from our coverage report (nan, gyp, etc).  I removed some dead code from `src/functions/copy` and then added some Note tests to boost up some 0 coverage files.
> Improve coverage

- lib/repository.js
- test/tests/checkout.js
- test/tests/merge.js
Checkout.head manipulates the index, where in these scenarios we only want to update the working tree. Tests now verify the index isn't changed when merging and checking out.
> Update Checkout and Merge

- vendor/libgit2.gyp
When compiling against the latest (0.22.1 currently) atom-shell
something was defining `HAVE_POLL` which is a linux system header
file. This was breaking the atom-shell build on windows.
> Fix atom-shell build on windows

- generate/templates/partials/sync_function.cc
- test/tests/oid.js
We will allow a user to pass a string as a valid parameter for any parameter that is a `GitOid`. In the function will will then convert that parameter to a `GitOid` and then free it after it's no longer in use. In a synchronous function we just did `free(&arg)` which was causing an issue in Windows. Now we'll appropriately cast that to a `void *` that will allow MSBUILD to free it without crashing.
> Fix freeing a `GitOid` that was passed as a string

- lib/status_file.js
- test/tests/status_file.js
Adds methods `inWorkingTree` and `inIndex` to StatusFiles. These just check it the status contains any WT_xxx status codes (or INDEX_xxx). It's very possible that a status could have both (eg if you've done a patch stage).
> Add convenience methods to status file

- generate/input/callbacks.json
The nodegit `git_diff_hunk_cb` wrapper had a definition for a `line` argument that is not present in the libgit2 API:
https://libgit2.github.com/libgit2/#HEAD/group/callback/git_diff_hunk_cb
This PR removes that `line` argument.
> Removed the superflous "line" argument

- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
- lib/rebase.js
- lib/repository.js
- lib/utils/normalize_options.js
- test/tests/rebase.js
+ `annotated_commit` was mistakenly named `annotated` in libgit2-supplement.json, and was thus not appearing in the NodeGit due to `annotated` being one of the removed groups. fixed the name.
+ added the `git_rebase_next` function to libgit2-supplment.json
+ updated descriptor.json for `git_rebase_commit`, `git_rebase_finish`, `git_rebase_free`, and `git_rebase_init`
+ fixed an issue with normalize_options.js causing errors if an instance of the Ctor was passed in
+ added Rebase convenience methods for normalizing options
+ added `rebaseBranches` and `continueRebase` convenience methods to `Repository` to help automate the rebase steps
+ added `/tests/rebase.js` for testing rebasing with and without the convenience methods
> Fix Rebase issues

- lib/tree.js
- lib/tree_entry.js
- test/tests/tree_entry.js
Fix for issue #570
If the entry path goes beyond the immediate children (a file in a subdir for instance) then path would return a path missing the subdir name
As an example:
getEntry("test/rawcommit.js") => entry path will be returned as "rawcommit.js"
> Fix path function in tree_entry (fix for issue #570)

- generate/input/descriptor.json
- lib/checkout.js
- test/tests/checkout.js
+ updated `descriptor.json` for `git_checkout_index` (was previously ignored)
+ added normalize option convenience method
+ added a test to make sure an index with conflicts will write to disk when checked out
This function is useful for easily writing merge conflicts to disk since both merge and rebase will throw the index when there are merge conflicts
> Added NodeGit.Checkout.index

- generate/input/descriptor.json
- lib/merge.js
- test/tests/merge.js
Enabled `git_merge` (NodeGit.Merge() and NodeGit.Merge.merge) and added a convenience method.
`git_merge` is the standard merge that merges into HEAD and writes the MERGE_* to the git repo which is the indicator that the repo is currently in a merge state. (`git_repository_state` looks for those files to determine if it's in a merge state)
Other merge methods, such as `Merge.commits` don't actually leave the repo in a merge state
> Standard merge

- generate/input/descriptor.json
- lib/cherrypick.js
- test/tests/cherrypick.js
Options wrapper and tests for `Cherrypick.cherrypick` and `Cherrypick.commit`.
Test for making sure cherrypick can be used to apply a stash.
Made `Cherrypick.cherrypick` async.
> Cherrypick tests

- test/tests/status_file.js
I'm adding test to check all Statuses, that have NodeGit.Status object. Currently, I skip statuses 'CURRENT' and 'WP_UNREADABLE', because it fails tests. Are they needed to implement different logic, then in checkStatusFile function?
> Rewrite test for statusFile

- lib/convenient_hunk.js
It returns an array of ConvenientLines, not Strings.
> Fix docs for ConvenientHunk#lines

- examples/general.js
- lib/repository.js
An enum value in libgit2 changed from `Reference.TYPE.ALL` to `Reference.TYPE.LISTALL`. Updated the example and the helper method to reflect that.
Also added in a catch to prevent an unresolvable symbolic ref from taking down the whole method.
> Update `Repository.prototype.getReferences` to use changed libgit2 enum

- lib/repository.js
- test/tests/rebase.js
The rebase convenience method (`repo.rebaseBranches()`) was not behaving as expect in fast-forward or no-op situations.
- For fast-forward, it was throwing an error, since `rebase.next()` throws an error if there's nothing to rebase. Now it checks to see if it can fast-forward before attempting the rebase, and if it can, it'll fast-forward.
- For no-ops ('ours' was already on top of 'theirs'), instead of doing nothing, it would rebase anyway, creating a new set of commits. Now it checks if it's already on top, and if it is, it won't rebase.
In both of situations, the 'ours' branch will be checked out, to match the behavior of rebase.
> Fix rebase convenience method for fast-forward and no-op situations

- generate/input/descriptor.json
- lib/convenient_hunk.js
- lib/convenient_patch.js
- lib/diff.js
- lib/repository.js
- test/tests/diff.js
This is a pretty big change to how we use diffs. Right now they are all synchronous and can take a long time to calculate if the diff is large (>1k changes).
This PR will make the diff/hunk/lines all async so that at least it's not blocking when it's doing its calculations. This will cause an API break so it makes us have to do a minor version bump.
Also, the "can find similar files in a diff" test in `test/tests/diff.js` was incorrectly passing before. I'm skipping it right now until we can figure out why it's not passing.
@orderedlist I know this will affect you and what you wrote so if you want to chime in on this feel free :)
> Make diff functions async

- lib/repository.js
Added the autoTag option to allow for automatic downloading of tags when executing Repository.fetch.
Fixes: #608
> Added the autoTag option to the Repository.fetch method

- generate/templates/partials/async_function.cc
```
The non-isolate version of node::FatalException() has been deprecated
in io.js; more precisely, it's deprecated in node.js v0.12 as well but
a bug in joyent/node prevents the deprecation warning from printing.
We don't have to catch exceptions ourselves.  Exceptions simply unwind
the stack until they encounter a try/catch block is encountered or the
fatal exception handler in the io.js or node.js run-time.
```
commit message modified from https://github.com/bnoordhuis/node-unix-dgram/commit/314858e9bab97d24e3a80c1dc67ffa5242c38e83
no tests fail. works the same for me.
though, I'm not sure how node-0.10 would work.
I think it'd be the same though - a fatal exception is a fatal exception.
> remove non-isolate FatalException

- README.md
i guess this was a typo, which results in unexpected output like `Foo Bar < foo.bar@example.com>` instead of `Foo Bar <foo.bar@example.com>`.
> fixed string concatenation

- generate/input/descriptor.json
- lib/commit.js
- lib/repository.js
- test/tests/commit.js
- test/tests/diff.js
The convenience function extends the original commit amend to accepts a tree object or a treeOid.
Also included is a test for the new commit amend function.
When testing the new function we noticed that the add commit test did not reset the head to the previous commit upon completion of the test. We modified that test to do so. This caused the "can diff with a null tree" test to fail since it was expecting 85 patches and resetting the commit test brought the number of patches to 84. We modified the test to expect the correct number of patches.
> Add amend commit convenience function 

- lib/repository.js
Hi guys,
The [Repository#checkoutBranch](http://www.nodegit.org/api/repository/#checkoutBranch) is marked `sync` in the docs, but it [returns a promise](https://github.com/nodegit/nodegit/blob/master/lib/repository.js#L1012).
I was hoping that this could fix that.
Thanks!
> docs: Marking Repository#checkoutBranch async

- lib/repository.js
- test/tests/repository.js
If you open a repo in NodeGit that's empty (i.e. has no commits yet)
doing `Repository.prototype.getHeadCommit` will error in the promise
chain. I think that really should just return null instead of killing
the promise chain.
There are also probably more of these in the library and we'll have
to add them as we find them.
> Fix `getHeadCommit` dying on empty repo

- lib/repository.js
`repository.rebaseBranches` will use the default signature if one isn't passed in, but `repository.continueRebase` didn't do that, and would fail if one wasn't provided.
continueRebase will now use the default signature if a signature isn't passed in.
> make signature optional for repository.continueRebase

- lib/status_file.js
`CONFLICTED` is the only Status that StatusFile didn't have a helper method for. Before, it could only be determined by doing `statusFile.status()` and looking for `CONFLICTED` in the result
> add statusFile.isConflicted

- lib/config.js
- test/tests/config.js
- `getStringBuf` is a method on Config's `prototype`, so the `getString` convenience method did not work. Fixed it to be on the prototype.
- We were getting false positives on the config tests because we were catching all errors with the `finallyFn`. Updated the tests the rethrow errors after the `finallyFn` is done.
> fix config.getString

- package.json
This should be the last bump to `nodegit-promise` before https://github.com/then/promise/pull/103 gets merged in hopefully.
> Move to latest `nodegit-promise`

- package.json
This makes our promisified functions use the latest `nodegit-promise` library (3.0.2)
> Bump `promisify-node` to 0.2.1

- .travis.yml
- appveyor.yml
- lifecycleScripts/checkPrepared.js
- lifecycleScripts/retrieveExternalDependencies.js
- package.json
This makes it way easier to deal with the electron (really, node-pre-gyp) madness, and everyone is cool with it.
- Updates the engines field in package.json
- Removes all of the references to (and handling for) legacy http_parser
- Removes 0.10 from test matrices
> Drop support for  node 0.10

- generate/input/descriptor.json
- test/tests/commit.js
NodeGit's http://www.nodegit.org/api/commit/#amend chokes if you give it a null update_ref value, but according to https://libgit2.github.com/libgit2/#HEAD/group/commit/git_commit_amend NULL is acceptable.
This PR changes update_ref to an optional parameter and adds a test.
> Allow update_ref to be null in Commit.amend

- examples/diff-commits.js
Previously, the patch and hunk info got printed before the lines that got changed; the output on master was
```
commit 59b20b8d5c6ff8d09518454d4dd8b7b30f095ab5
Author: tbranyen <tim@tabdeveloper.com>
Date: Sat Apr 09 2011 01:48:49 GMT+0100 (BST)
Updated gitignore and raw-commit test
diff .gitignore .gitignore
diff test/raw-commit.js test/raw-commit.js
@@ -1,4 +1,5 @@
@@ -2,7 +2,6 @@ var git = require( '../' ).raw,
.lock-wscript
-./build/
-./doc
-!./doc/Theme.css
+build
+doc
+!doc/Theme.css
+example/stress/test
rimraf = require( '../vendor/rimraf' ) || require( 'rimraf' ),
path = require( 'path' );
-console.log(git);
var testRepo = new git.Repo();
// Helper functions
```
The output is now as expected (ignoring the first lines):
```
diff .gitignore .gitignore
@@ -1,4 +1,5 @@
.lock-wscript …
```
> Printing patch and hunk info at correct place.

- lib/convenient_line.js
- lib/repository.js
Fixes bug that involves staging lines:
- User can stage '\ no newline at end of file'. Shouldn't happen!
- Last character in a diff gets cut off if it's the last line in file.
- Staging the last line with no \n will magically add a newline. Shouldn't happen.
> Stage line eof bug

- lib/repository.js
- test/tests/stage.js
This one's better. Accounts for a case I haven't considered previously.
Basically added
```
if (hunkLine.raw.content().indexOf("\\ No newline at end of file") != -1) {
return false;
}
```
in `Repo.prototype.stageLines`'s `processSelectedLine`. This replaces a similar check for `\\ No newline at end of file` I originally had in `Repo.prototype.stageLines`.
> Stage line eof bug part 2

- vendor/libgit2.gyp
This a workaround for the compilation
error with Node 4:
../vendor/openssl/openssl/ssl/s3_clnt.c:3262:60: error: use of undeclared identifier 'EVP_PKT_EXP'
Node 4.0.0 includes openssl 1.0.2d, which
no longer defines EVP_PKT_EXP and friends.
node-gyp puts header directories supplied
by node first, therefore OpenSSL include
files shipped by node are used, and
not the ones from the embedded OpenSSL
source.
> Node 4: Use embedded OpenSSL headers first

- generate/templates/partials/field_accessors.cc
When compiling with clang we are getting:
../src/checkout_options.cc:536:39:
error: invalid operands to binary expression
('size_t' (aka 'unsigned long') and 'nullptr_t')
This commit improves the generated code.
> Fix error: invalid operands to binary expression ('size_t' (aka 'unsigned long') and 'nullptr_t')

- appveyor.yml
Use Gyp environment variable to
set up the compiler (as we don't pass
npm parameter to node-gyp).
> Clean up AppVeyor environment

- lifecycleScripts/install.js
By the time "install" lifecycle script
is invoked npm already has installed
all the dependencies.
> Drop recursive npm install

- .gitignore
- generate/templates/templates/binding.gyp
- vendor/libgit2.gyp
- gyp generates full paths where necessary
- keep generated .vcxproj files in the build directory
- don't set ObjectFile path to "$(IntDir)/%(RelativeDir)/",
because win_delay_hook has an absolute path in %(RelativeDir)%
which causes
MSB3191 Unable to create directory: The given path's format is not supported
(https://github.com/nodejs/node-gyp/issues/732)
> Use relative paths for dependencies

- lib/repository.js
- test/tests/stage.js
Upon staging a hunk/line, stage the whole file if:
* It is the last hunk/line, ie the result of 
```Diff.indexToWorkdir(repo, index, {
flags:
NodeGit.Diff.OPTION.SHOW_UNTRACKED_CONTENT |
NodeGit.Diff.OPTION.RECURSE_UNTRACKED_DIRS
})```
will be a diff containing a single patch with _no hunks_.
* The file does not have filemode (permission, type) changes.
> Stage last hunk? No empty diffs!

- README.md
The example is importing relative when it should import the named module.
> Fix import path in example

- test/tests/diff.js
Number of patches returned is 84 or 85 depending on something unknown at this time.  Hopefully we can eventually resolve the root cause of the difference.
> Modified "Diff can diff with a null tree" test.

- lib/revwalk.js
- test/tests/revwalk.js
Libgit2 throws E_ITEROVER at the end of traversals, we need to catch that error and treat it as the end of a traversal from now on.
> Handle ITEROVER properly in RevWalk

- examples/fetch.js
Fetch requires the credentials function to be wrapped in the callbacks object (otherwise the promise succeeds even though it has failed silently).
> Fixed fetch call.

- generate/templates/manual/include/functions/sleep_for_ms.h
- generate/templates/manual/src/functions/sleep_for_ms.cc
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/templates/binding.gyp
- generate/templates/templates/class_content.cc
- generate/templates/templates/struct_content.cc
We're using our own thread sleep function which I think removes the need now for using c++11. Hopefully this will fix everybody's build errors and we'll have rainbows and lollipops and unicorns instead.
> Remove c++11 dependency

- generate/input/descriptor.json
- lib/convenient_patch.js
- test/tests/patch.js
I've just added support for the git_patch_line_stats method.
The only caveat is that the returned values are size_t being cast to a js number.
This is convenient to quickly gather stats about the patches without having to go down to the line level.
Added a simple test for the function as well
> Add support for patch method git_patch_line_stats + test for it

- generate/templates/manual/revwalk/fast_walk.cc
- package.json
When I wrote `RevWalk.prototype.fastWalk` I assumed that `git_err_last` would not
be null when `GIT_ITEROVER` was the result. I was wrong :(
> Fix error detection in `fastWalk`

- .travis.yml
- appveyor.yml
Building nodegit locally in the absence of a prebuilt binary is still a complicated task 😰. By adding Node v5 support to the CI builds now we can get the prebuilt up on S3 quickly.
> Node v5.0 (modules v47) to allow prebuilt binaries in S3.

- lifecycleScripts/install.js
When downloading from aws via node-pre-gyp fails, we should log the reason for the failure. #758
> Log error when downloading from aws

- appveyor.yml
What it says above. Needed so we can get all the binaries out there.
> Build both x86 and x64 on appveyor

- lifecycleScripts/install.js
- package.json
As of https://github.com/mapbox/node-pre-gyp/pull/175, node-pre-gyp now understands “electron” as a runtime.
This doesn’t actually create and publish Electron builds—I’ll work on that next—but it does mean that nodegit will try to use a prebuilt binary and then simply fallback to source.
(Context: we’re investigating bundling nodegit in Atom, but CI times explode without nodegit binary support: https://github.com/atom/atom/pull/9213.)
> Allow node-pre-gyp for Electron and node-webkit

- lib/utils/normalize_options.js
- test/tests/diff.js
It's possible to have some options (DiffOptions, for example) where `options[key]` is undefined. There's no reason why undefined options should be passed to any of nodegit's class methods. Let's check for them in `normalizeOptions`, and prevent these undefined options from being copied.
I didn't check for `null`, since for some options, `null` is ok.
> Ignore undefined options in normalizeOptions.

- .travis.yml
This PR cleans up the TravisCI manifest file. e.g. installing `nvm` on Linux is unnecessary because it's preinstalled, lcov should only be installed if it is actually needed, ...
> TravisCI manifest cleanup

- package.json
Fixes issues where promises that resolve to promise chains could end up in an invalid state where they were neither pending, fulfilled, nor rejected.
> Bump nodegit-promise to 4.0.0 and Promisify to 0.3.0

- generate/scripts/helpers.js
- test/tests/oid.js
- test/tests/refs.js
This should fix #800. The issue was that the second argument was marked as `isSelf`in the following methods. So comparing two objects really just compared an object to itself.
From what I could tell this will only change the following:
- `Hashsig#compare`
- `Oid#cmp`
- `Oid#equal`
- `Oid#ncmp`
- `Reference#cmp`
- `Strarray#copy`
> Added missing arguments to compare

- TESTING.md
- test/tests/tree_entry.js
The last one, in fact. I was trying to get the grasp of it. Once I know how it goes, I'll try for a few more. Checks pass and the "missingTest" entry is, in fact, missing now.
> Add `TreeEntry` file length test

- lib/repository.js
- test/tests/rebase.js
This adds support for a callback parameter that can be passed to `rebaseBranches` and `performRebase`.  The callback allows the caller to perform actions between steps of the rebase (between calls to `next`).
> Add beforeNextFn callback for rebase

- .npmignore
- lifecycleScripts/install.js
- package.json
`node_pre_gyp` [will parse `npm_config_` environment variables](https://github.com/mapbox/node-pre-gyp/blob/cfefa6f6197748d50980c5e49dc57c44ef3efc70/lib/node-pre-gyp.js#L130) to determine if the runtime is node/electron/nwjs. So nodegit doesn't need to do any special detection itself.
This supersedes #804.
> Let node-pre-gyp handle Electron/nwjs

- generate/input/callbacks.json
- generate/input/descriptor.json
- generate/scripts/helpers.js
- generate/templates/manual/include/typedefs.h
- generate/templates/templates/class_header.h
- lib/submodule.js
- test/tests/submodule.js
A lot of this is to work around the fact that `git_submodule_foreach`’s callback isn’t `typedef`’d. That’s fixed in https://github.com/libgit2/libgit2/pull/3539, but there hasn’t been a release including it yet. So in the mean time, we need to do a little extra futzing.
> Add submodule foreach

- generate/input/descriptor.json
- test/tests/treebuilder.js
TreeBuilder.create(repo, null) should be allowed, since this is the method required to create new directories in any tree, or the initial tree for the initial commit of a repo.
In this branch I've specified that `source` is optional (though you still need to send `null` or it will throw `Error: Callback is required and must be a Function` - @maxkorp stated that this is a semi-known issue with the promisifier).
The tests are an initial set for Treebuilder: check it can create a new Tree, and check it can be created from an existing tree and verify it has the correct number of entries. I plan to add more tests verifying it can add and read specific types of entries, but that's unrelated to this fix.
> TreeBuilder.create has source as optional param, plus associated tests

- lib/repository.js
In repository.fetch don't swallow errors thrown by remote.fetch, catch them, pass them to the callback and then rethrow them.
There is a failing test "can reject fetching from private repository without valid credentials" for remote.js but that is not caused by this work.
Helps with https://github.com/nodegit/nodegit/issues/742
> In repository.fetch don't swallow errors thrown by remote.fetch .

- .travis.yml
- CHANGELOG.md
- README.md
- lifecycleScripts/install.js
- package.json
Fixes an issue where when manuallybuilding after a failed download, `"undefined"` would sneak in to the arguments for node-gyp. Also updates missing changelog entries (not including 0.5.x) and bumps to 0.6.3
> Fix manual install

- generate/templates/manual/revwalk/fast_walk.cc
- generate/templates/partials/async_function.cc
- generate/templates/partials/sync_function.cc
- generate/templates/templates/nodegit.cc
- generate/templates/templates/nodegit.js
This addresses a bug that would happen occasionally during rebase - because `Rebase.next` doesn't set or clear `giterr_last` when it returns `GIT_ITEROVER`, we would pick up a stale error if one was previously left in that thread.  `performRebase` would then get the stale error instead of `GIT_ITEROVER` and not finish correctly (https://github.com/nodegit/nodegit/blob/d1201998a6fe64e35cf8c357b3dd94d2f6982bc0/lib/repository.js#L904-L908).
I am not sure whether this is the best way to fix this, and if it is, whether similar adjustments need to be made in other places in code.  For example, https://github.com/nodegit/nodegit/blob/d1201998a6fe64e35cf8c357b3dd94d2f6982bc0/generate/templates/partials/sync_function.cc#L66-L70 accesses `giterr_last` where `result` could be `GIT_ITEROVER`.
An …
> Omit baton->error on GIT_ITEROVER

- generate/input/descriptor.json
- generate/templates/partials/async_function.cc
- test/tests/graph.js
1. Add a new template for mixed result/error code return values from libgit2 for async code.
2. Make git_graph_descendant_of use the new async template.
> Asyncify graph descendant of

- lib/convenient_line.js
- lib/repository.js
- test/tests/commit.js
- test/tests/convenient_line.js
- test/tests/diff.js
- test/tests/stage.js
This changes how `ConvenientLines` are calculated with a breaking API change.
`ConvenientLine` used to assume that all content coming back was ASCII characters and
a uniform byte length. This is no longer the case. Now we use the byte length coming
back from libgit2 to extract the string from a buffer using the correct byte length. This
will give back the correct line everytime.
~~The breaking API change is that we no longer return the new line character with the line
nor do we include that character in the `contentLen` calculation either. I'm on the fence
about that change but it seems like it's what we ought to be doing instead of force all of
the consumers of the library to account for that everywhere.~~
Edit: I reverted the change to returning the new line characters.
> Modify `ConvenientLine` to work with unicode

- examples/clone.js
- examples/pull.js
[This line] (https://github.com/nodegit/nodegit/blob/232dbb19116c58d22cd7afd7435ee0bbe063f85b/lib/repository.js#L688) and my own trial and error with a project leads me to believe the auth callbacks need to be nested under the `callbacks` key in fetch options.
This also [applies](https://github.com/nodegit/nodegit/blob/44779afd0d460011e13a5cba9a47a48119aa472e/lib/clone.js#L31) to the clone example I think, though it requires a structure of fetchOpts.callbacks.<authCallback>.
> Fix pull and clone example fetchOptions structure

- examples/walk-history-for-file.js
The walk-history-for-file.js example was broken so I fixed it with some minor changes. The reason it broke is that ```diff.patches()``` returns a promise and not an array that can be reduced. I made the example a little bit less efficient (checking for an already present commit) but I think it is a little bit more readable. The screenshot shows a comparison of ```git log``` and the example. Note that it is not a 1-1 mapping because git log is a little bit more intelligent.
```output of git log descriptor.js```
```output of walk-history-for-file.js```
> Fixed example walk-history-for-file.js

- lifecycleScripts/install.js
For better Windows support.
Fixes #850
> Wrap toolPath in quotes instead of escaping spaces

- lib/repository.js
- test/tests/stage.js
...as well as just a string.
There is a case in GK where `Repository.prototype.stageFilemode` gets called a bunch of times (once for every file in working directory, for instance). This wastes resources. `stageFilemode` should be able to accept a single path as string or multiple paths as array, then stage/unstage filemode changes for files specified as usual.
> Extend stageFilemode to accept array of paths

- examples/cloneFromGithubWith2Factor.js
- guides/cloning/README.md
- guides/cloning/gh-two-factor/README.md
- guides/cloning/gh-two-factor/index.js
- guides/cloning/index.js
- guides/cloning/ssh-with-agent/README.md
- guides/cloning/ssh-with-agent/index.js
Related to https://github.com/nodegit/nodegit/pull/647#issuecomment-142915106 and #848
The fixes similar to #848 is applied to cloning with two factor authorization as well.
And if you use `fetchOpts` you don't need a URL with a token any more.
> Fix clone options in two factor authorization

- generate/input/descriptor.json
- test/tests/submodule.js
This makes a number of NodeGit functions related to adding / opening / initializing a submodule async.  This is to better process the return value (getting a promise rejection with an error message instead of a numeric error code), and to reflect that the methods are affecting the repo in the file system.
Also added a test which exercises most of the affected functions (except for `update` - I am getting crashes on `update` that I still need to dig into, but the new NodeGit signature of the function should be correct).
> Make submodule init / setup functions async

- generate/templates/manual/include/lock_master.h
- generate/templates/manual/src/lock_master.cc
This fixes a small but serious bug in the new thread safety code, introduced in https://github.com/srajko/nodegit/commit/dbce34f9f6298c6df80f2e0771dcafef51a6c35f
The referenced commit moves the call to `ConstructorImpl` before `AddParameters`, because `AddParameters` relies of `impl` being initialized, and `ConstructorImpl` initializes `impl`.  Unfortunately, `ConstructorImpl` was also calling `Lock`, and after this change `Lock` was doing nothing because `ObjectsToLock` calls happen in `AddParameters`, which was now happening later.
This PR moves the `Lock` call into a new `ObjectsToLockAdded` method, which is called after `AddParameters`.
I will try to add some testing for the locking itself (in a separate PR, to not tie this up)... it might be hard to do detailed testing from JS, but …
> Call Lock after objects to lock have been added

- generate/templates/manual/include/lock_master.h
- generate/templates/manual/src/lock_master.cc
- generate/templates/templates/nodegit.cc
- test/runner.js
- test/tests/index.js
- test/tests/thread_safety.js
Exposes a few thread safety internals so they can be at least somewhat tested.
Also adds support for an environment variable `NODEGIT_TEST_THREADSAFETY`, which when set will enable thread safety for the run of the test suite.
> Add rudimentary diagnostics and testing for thread safety code

- .travis.yml
Is it really this easy?
*... probably not!*
> Configure travis to not use coverage and gcc4.9 during tagged releases

- lib/index.js
Now that https://github.com/libgit2/libgit2/issues/2687 has landed we don't need our hack to speed up `Index#addAll` anymore.
This fixes #751
> Remove `Index#addAll` hack

- generate/input/descriptor.json
- lib/revert.js
- test/tests/revert.js
Updated Revert.revert and Revert.commit to both be async. Set merge_options to be optional.
Testing that Revert.revert properly updates the working directory and stages files in the index.
> Tests for Revert.revert

- examples/walk-history-for-file.js
- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
- generate/templates/manual/revwalk/file_history_walk.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/struct_header.h
- lib/revwalk.js
- test/tests/revwalk.js
Implementing file history walk for revwalk. You pass it a sha, it then traverses until it either finds the 'added' entry for the file OR it hits the max number of commits to search for history.
> Implement file history walk in revwalk

- lib/commit.js
- lib/convenient_hunks.js
- lib/convenient_patch.js
- lib/diff_file.js
- lib/repository.js
Fixes a variety of documentation issues:
* Fixes cases where the docs said `Ref`, but meant `Reference`.
* Adds documentation for `DiffFile`.
* NOTE: There's a bug in your doc generator, which causes `DiffFile` to display the invalid instance fields alongside my correct methods.
* Fixes `exports.module` => `module.exports` in a few places.
Let me know if you want me to squash these into one commit.
> Fix documentation issues

- generate/templates/manual/revwalk/file_history_walk.cc
- lib/revwalk.js
- test/tests/revwalk.js
Only calculate full diffs (without pathspec) in case we believe there is a rename.
> Optimize rename detection in historywalk

- lib/repository.js
There were a couple funny things:
1. Removing the index lock seems out of place for this function.
2. We should calculate the diff *after* refreshing the index.
> Fix stageLines

- generate/templates/manual/src/convenient_patch.cc
If content isn't greater than 29, don't search for the no newline token. This lead to segfaults on linux. Interestingly, this did not affect most OSX and Windows machines. Some sort of compiler-saving-of-the-day?? No clue.
> Don't check for \\ No newline at end of file\n if it can't exist

- generate/templates/manual/revwalk/fast_walk.cc
In the error state, fast walk would just do an equality check instead of an assignment of the error. I'm an idiot :(
> Fix `fast_walk.cc` when there was an error

- generate/templates/manual/include/init_ssh2.h
- generate/templates/manual/src/init_ssh2.cc
- generate/templates/templates/binding.gyp
- generate/templates/templates/nodegit.cc
- lifecycleScripts/configureLibssh2.js
- lifecycleScripts/install.js
Provide openssl with the locking setup it needs for thread safety.
Initialize libssh2 to avoid the possibility of its subsequent thread-unsafe init.
> OpenSSL and libssh2 thread safety

- lib/repository.js
Some methods were incorrectly labeled sync instead of async.
> Fix docs on `Repository`

- generate/templates/templates/nodegit.cc
There was a linking exception that was fixed by changing the order of includes for node and v8 headers
> Fix debug build on windows

- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
We were passing back the memory address that was actually controlled by V8 to all C/C++ callbacks which could get randomly moved by V8 at random times causing random segfaults randomly.
http://i.imgur.com/rB4Hux7.gif
> Fix callback out values in callbacks from C++

- vendor/libgit2.gyp
Hi,
Atom crashed because of https://github.com/atom/atom/issues/10965
Here's the same fix we've used for git-utils https://github.com/atom/git-utils/pull/61
Full story about this bug in libgit2 issues tracker here https://github.com/libgit2/libgit2/issues/2586
Please review as this makes library unusable in a lot of use-cases. :(
> Fix compilation for systems != windows and crash in diff function

- generate/templates/partials/convert_from_v8.cc
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/struct_content.cc
- generate/templates/templates/struct_header.h
Using `GetRefValue` would return the V8 handled pointer instead of the pointer to the libgit2 value and the V8 handled pointer could be changed at any moment.
Removing this function and setting the pointer value to the underlying C object will prevent V8 GC screwing up a NodeGit app.
> Remove `GetRefValue`

- lib/repository.js
And avoid trying to call a method on a boolean when isBranch() is false.
> make checkoutBranch works with branches that lives outside of refs/heads

- lib/repository.js
- test/tests/repository.js
I'm not sure if this is the intended behaviour, but my take on it as a convenience method it should be able to handle creating the initial commit on a empty repo.
> fixes #852 should not be an array with null in it

- .jshintrc
- lib/tree.js
- test/tests/tree.js
- test/utils/repository_setup.js
Fix for https://github.com/nodegit/nodegit/issues/928
This is the non-api breaking change.
How does anyone feel about changing `walk` to return a promise (with a `progress` callback) instead of an event emitter? (ex: `tree.walk().then(entries => ...)`)
> Fix tree.walk() and add test

- lib/diff.js
- test/tests/diff.js
libgit2 wants the string’s byte count, while `String.length`gives us the number of characters. These aren’t necessarily the same thing in unicode land.
> Fix diffing blobs to buffers with unicode

- lib/merge.js
Clarify that their commit should be an `AnnotatedCommit` not a `Commit`
> Docs: improved Merge.merge param docs

- .travis.yml
- appveyor.yml
- vendor/http_parser/.gitignore
- vendor/http_parser/AUTHORS
- vendor/http_parser/Makefile
- vendor/http_parser/README.md
- vendor/http_parser/contrib/url_parser.c
- vendor/http_parser/http_parser.c
- vendor/http_parser/http_parser.h
- vendor/http_parser/test.c
Bumping `http-parser` to 2.6.1 broke fetching/pulling from bitbucket in earlier versions of node somehow. This undoes that change and we'll have to look into fixing node v5.6.x later.
> Revert "Merge pull request #931 from nodegit/bump-http-parser"

- generate/templates/manual/src/convenient_patch.cc
[Libgit2 documents](https://github.com/libgit2/libgit2/blob/d8f721592817cb300339c827579bc545844b276f/include/git2/diff.h#L555) that `content` isn’t NUL-terminated, so we can’t
call `strlen` on it. If we do, we’ll probably crash.
> Fix patch crash

- lib/stash.js
I tried to use `nodegit.Stash.apply` and it crashed... Looks like `NodeGit.CheckoutOptions` wasn't capitalized like it should've been.
> Stash.apply: Fix a typo in arguments to normalizeOptions

- generate/templates/manual/include/wrapper.h
- generate/templates/manual/src/convenient_patch.cc
- generate/templates/manual/src/wrapper.cc
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/convert_to_v8.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/struct_content.cc
- generate/templates/templates/struct_header.h
Ran into this as part of https://github.com/nodegit/nodegit/pull/955.
Changing the `raw` pointer from `void *` to `const {{ cType }} *` to add type safety.  The change actually caught a problem in `struct_content.cc` where we were sometimes taking the address of a pointer and passing that in instead of the pointer (for `git_checkout_options.baseline`, we were sending in a `git_tree **` instead of a `git_tree *` to `New`).
> Use type safe pointer instead of void * for New

- lib/diff.js
Been seeing some strageness with `blobToBuffer` (see the issue I created over here, for example: https://github.com/nodegit/nodegit/issues/963 )
This pull requests fixes the fact that if you pass in an object of type Buffer, it is turned into a string, but then that string is never used (and because of the way the C bindings are written, because the object isn't of type string, it gets turned into a null, and you get a diff that looks like there's no content in the file.)
> diff.blobToBuffer: Fix passing in Buffers instead of strings.

- generate/templates/partials/convert_from_v8.cc
This is a pull request to fix the issue I created over here: https://github.com/nodegit/nodegit/issues/965
To summarize over here why I'm making these changes:
- `strdup` expects a C-style null-terminated string, but sometimes we're using nodejs strings to pass in strings that contain nulls in the middle, thus failing to copy everything at best, and causing crashes from reading invalid memory locations at worst.
- Thus I changed to using `malloc`, `memcpy` and `memset` to prevent these issues.
To explain my changes a little bit:
- I make the malloc'ed string one byte longer so I can add a terminating null character, since it looks like these templates are used in a number of different places, and for things like a repo path, where we _do_ want things to end in a null character.
- I used …
> Switch from strdup to memcpy to faithfully copy all bytes and prevent a crash in some cases.

- package.json
- postinstall.sh
`nodegit` is usually used as library for other projects. Nodegit is also, unfortunately, depends on a version of libstdc++ that is not installed on many linux systems. Any person that uses nodegit as a library would need to explain this problem in their issues. In order to reduce the work of libraries/tools that depend on nodegit this PR adds an error message on postinstall if the dependency is missing and adds steps on how to mitigate that issue.
_Note: This has been a follow-up on #969._
> Error message on libstdc missing.

- generate/input/descriptor.json
- test/tests/ignore.js
Since it’s potentially doing IO and touching global state, it should be async.
> Make Ignore.pathIsIgnored async

- generate/templates/manual/include/lock_master.h
- generate/templates/manual/src/lock_master.cc
- generate/templates/partials/async_function.cc
- generate/templates/partials/sync_function.cc
- generate/templates/templates/nodegit.cc
- test/runner.js
- test/tests/index.js
- test/tests/thread_safety.js
Adds a middle-ground thread-safety level, which locks async functions but skips locking of sync functions, to avoid the risk of blocking the main thread.
/cc @johnhaley81 @joshaber
> Add support for thread safety on async actions only

- .travis.yml
- lifecycleScripts/install.js
includes workaround which symlinks /usr/include/asm to /usr/include/asm-generic, see https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/825574/comments/2
**caveat**: You cannot run tests on the 32-bit binary because it simply won't load on the 64-bit Travis system.
> build: build and publish binaries for 32-bit systems

- generate/input/descriptor.json
- generate/templates/manual/include/functions/copy.h
- generate/templates/manual/src/functions/copy.cc
- generate/templates/partials/convert_to_v8.cc
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
- test/tests/commit.js
- test/tests/remote.js
- test/tests/revwalk.js
- test/tests/submodule.js
- test/utils/garbage_collect.js
Makes remotes self-freeing.
I needed to add new functionality for https://libgit2.github.com/libgit2/#HEAD/group/remote/git_remote_get_refspec, because the returned refspec belongs to the remote (and gets freed with it), but there is no way to duplicate the refspec (it is an opaque struct).  AFAICT this requires an ownership mechanism, allowing the refspec to keep a handle on its owner remote so it doesn't get freed.
So I extended `shouldDuplicate` into `ownedByThis`: when `ownedByThis` is turned on we duplicate if the type has a `dupFunction`, otherwise we keep a handle on the owner.
> Remote leak fix

- examples/add-and-commit.js
- examples/create-new-repo.js
- examples/details-for-tree-entry.js
- examples/general.js
- examples/index-add-and-remove.js
- examples/merge-cleanly.js
- examples/merge-with-conflicts.js
- examples/push.js
- examples/remove-and-commit.js
- generate/input/descriptor.json
- lib/repository.js
- test/tests/checkout.js
- test/tests/commit.js
- test/tests/diff.js
- test/tests/index.js
- test/tests/merge.js
- test/tests/patch.js
- test/tests/rebase.js
- test/tests/reset.js
- test/tests/revwalk.js
- test/tests/stage.js
- test/tests/submodule.js
- test/tests/thread_safety.js
- test/utils/repository_setup.js
`Repository#refreshIndex` will return an `Index` object back that has the latest data loaded off of disk.
This removes the need for the `Repository#index` then `Index#read(1)` pattern that was being used which seemed to have some weird timing issues that could have wrong data loaded into the returned index.
Calling this function also clears the `Index` that's cached in the `Repository` object.
> Add `Repository#refreshIndex`

- lib/repository.js
We should be using `Repository#index` or `Repository#refreshIndex` instead. All our code/examples have already been updated to use them.
> Remove `Repository#openIndex`

- generate/input/callbacks.json
- generate/templates/manual/include/async_baton.h
- generate/templates/manual/include/callback_wrapper.h
- generate/templates/manual/include/lock_master.h
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/struct_content.cc
- generate/templates/templates/struct_header.h
- test/tests/clone.js
This reverts the removal of throttling, and adds two changes that seem to resolve the crash.  The likely fix is https://github.com/nodegit/nodegit/commit/1e585eae28fae98e1807cf20d88e643dae5cf7de, which restores some logic I omitted in the refactoring, thinking it should not make a difference... but it looks like it did.
I am a little worried about the state of the raw object making a difference after its wrapper has been destroyed, but maybe I'm just missing the big picture of what's happening here.  In any case, the logic matches what we were doing before, and no crash is better than crash.
> Throttle callbacks (again) + crash fix

- generate/templates/filters/args_info.js
- generate/templates/partials/async_function.cc
- test/tests/branch.js
The generated C++ code was freeing the out parameter because it was a string even though the string was of type `const`. Now we have a safeguard in place so we aren't freeing things that we shouldn't be in this case.
> Fix segfault in `Branch.name`

- generate/input/descriptor.json
- generate/scripts/generateNativeCode.js
- generate/scripts/helpers.js
- generate/templates/manual/include/nodegit_wrapper.h
- generate/templates/manual/src/nodegit_wrapper.cc
- generate/templates/partials/traits.h
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/struct_content.cc
- generate/templates/templates/struct_header.h
- test/tests/repository.js
Starts towards more code sharing between the struct_* and class_* combyne templates - I needed this to make the new memory management code available to structs (it was only implemented for classes initially).  There is probably more code that could be pulled in down the line but I wanted to keep this minimal for what I needed.
This leans more heavily on C++ templates than NodeGit code typically does, so this is something to consider - if needed I can probably get similar code sharing via combyne partial templates but I'd prefer to use language features when reasonable.  v8 and Nan do use C++ templates / traits classes in similar ways, so at least it's not a completely new pattern to the project.
See code / commit comments for more details on the changes.
> Factor out base class for structs / classes with cType

- generate/input/descriptor.json
when you run into a conflict, sometimes one of the entries just plain old doesn't exist. An example being you create a file in 2 branches and try to merge them. They have no ancestor_entry because they were both created in their respective branches. Therefore, ancestor_entry should be null. The same can apply to our_entry and their_entry
> Index.conflictAdd should have nullable entries

- generate/templates/templates/struct_content.cc
Fixes a memory leak when ignoreinit was used (as described in deleted comment).
> Ignoreinit leak fix

- lib/commit.js
`Commit#getDiffWithOptions` did not use the diff options passed in if the commit did not have a parent.
> Use diff options even if the commit has no parent

- generate/input/libgit2-supplement.json
- test/tests/commit.js
Better wrapping of reflog entry methods.  Will also help with #1006, so we're not lying when we say that for example `git_reflog_entry_id_new` returns an `oid` "ownedByThis" (this PR will make "This" the reflog entry).
> Move reflog entry methods to ReflogEntry

- .travis.yml
- appveyor.yml
~~People upgrading from 0.10/0.12 are probably going to be going to either Node 5/6 and not Node 4. Our build matrix is getting huge and I'd like to build binaries for Node 6 now. Thus I figured we could drop support for Node 4.~~
Put support for Node v4 back in.
> Add Node 6 support

- generate/input/descriptor.json
- test/tests/stage.js
Creating a commit should be an async action, this makes it so.
> Make `Commit.create` async

- generate/input/descriptor.json
Does not modify code generation since previously the string "true" evaluated to truthy
> Set oid.selfFreeing to true instead of "true"

- generate/templates/manual/src/nodegit_wrapper.cc
If trait is owned and is non-duplicable, disallow it from marking itself as selfFreeing
> Memory management: Self freeing fix

- lifecycleScripts/submodules/getStatus.js
When installing NodeGit from npm as a dependency if the user had to build the binary it would fail on the submodule check. Now we just bypass that check on and error since the package would be published with the correct version of libgit2 in it and we don't need to grab it as a submodule at that point anyways so the check and logic is useless.
> Fix submodule check

- lib/commit.js
1. It doesn't take a callback
2. Possessive form needs a single quote instead of a double quote.
> Fix two typos in the documentation for Commit#parents:

- generate/input/libgit2-supplement.json
- lib/rebase.js
- lib/repository.js
Merge options should be exposed in rebase options, so that rebases are more configurable.
Also exposes diffOptions flags field to the public anywhere NodeGit uses NodeGit.Diff methods that have options.
> expose merge options and diff flags

- generate/templates/manual/include/nodegit.h
- generate/templates/manual/revwalk/fast_walk.cc
- generate/templates/partials/async_function.cc
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/templates/class_content.cc
- generate/templates/templates/nodegit.cc
- generate/templates/templates/struct_content.cc
In v8 5.2 (modules v49), Get/SetHiddenValue are removed (they've long been deprecated). But, the replacements (Get/SetPrivate) don't exist in node 4's version. NAN is planning on supporting this eventually (see: https://github.com/nodejs/nan/issues/587), but we need something shorter term as electron 1.3 has already bumped v8. 
Fixes https://github.com/nodegit/nodegit/issues/1089
> Preempt nan to fix deprecated calls to Get/SetHiddenValue

- generate/input/descriptor.json
- generate/templates/manual/include/functions/copy.h
- generate/templates/manual/src/functions/copy.cc
- test/tests/signature.js
It's unsafe to use the signature's time directly since the signature could be freed. Instead duplicate the signature's time when it is requested and set it to `selfFreeing`.
> Memory management: duplicate time

- README.md
The Circle CI instructions should be pretty obvious given the Ubuntu instructions, but this might save some people forgetting the -y flags or no knowing which part of the circle.yml to do this install in.
> Added instructions for CircleCI users

- .travis.yml
- appveyor.yml
- generate/templates/templates/binding.gyp
6.3 is working for me locally now, so trying this here.
> Try re-enabling node 6.3

- vendor/libssh2/win32/libssh2_config.h
When building with the windows SDK for vs2015, the build would die due to some duplicate defines. 
Found a variation of this patch on github.com/libssh2/libssh2 for libssh2 1.7, which we still need to update to, but for now this works.
> patch libssh2 to work with vs2015

- lifecycleScripts/postinstall.js
- utils/buildFlags.js
Since we can't require it from node if it's compiled for electron, we should just assume success for now
Addresses https://github.com/nodegit/nodegit/issues/1095
> Don't run postbuild when we detect electron install

- package.json
- test/tests/cred.js
- vendor/libgit2.gyp
Compile libgit2 with GIT_SSH_MEMORY_CREDENTIALS defined to allow
sshKeyMemoryNew to work.
Fixes #760
> Define GIT_SSH_MEMORY_CREDENTIALS for libgit2

- test/tests/clone.js
Because the SSH stuff is documented with the tests at the moment it helps out if the var names are a bit clearer.
> Add "Path" to ssh variable names in tests for clarity

- generate/templates/templates/binding.gyp
Even though we had the `/EHsc` option in the `gyp` file, it was not being applied correctly.  With the change, the option does get applied, which also takes care of numerous build warnings like this one:
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtree(839): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\lock_master.cc) [C:\projects\nodegit\build\nodegit.vcxproj]
```
> Fix windows exception handling

- TESTING.md
Changed a link to point internally instead of unnecessarily using an
external link.
> Fix incorrect anchor link in TESTING.md

- README.md
Users can't access https://libgit2.slack.com/ directly. They need to go to http://slack.libgit2.org/ first to get an invitation. This information should be reflected in the `README.md`.
> README.md needs to show where to get Slack invitation

- lib/checkout.js
The docs incorrectly spec that an `Oid` can be used as a `treeish` but the libgit2 [`git_checkout_tree`](https://libgit2.github.com/libgit2/#HEAD/group/checkout/git_checkout_tree) API actually only supports "a commit, tag or tree".
The following code will reproduce the problem.
```
> node bug.js
[Error: Object to checkout does not match repository]
```
```JavaScript
var git = require("nodegit");
git.Repository.open("myrepo")
.then(function(repo) {
return repo.getTagByName('v1.0.0').then(function(tag) {
git.Checkout.tree(repo, tag.id(), { checkoutStrategy: git.Checkout.STRATEGY.SAFE_CREATE })
.then(function() {
console.log("ok");
}).catch(function(err) {
console.log(err);
});
});
});
```
> Checkout's tree(*) function does not support Oid as a parameter

- lifecycleScripts/postinstall.js
After installing `nodegit` in a directory which had spaces along its path, the postinstall script crashed as a result (`Error: Cannot find module 'C:\<path up to the first space>'`) - wrapping this `node` call's target in quotes fixes the issue.
> Fix postinstall script crash when install location has spaces in its path

- lib/tree.js
Fix the documentation generation for Tree's getEntry method so that it'll be properly tagged as ASYNC in the [output](http://www.nodegit.org/api/tree/#getEntry).
This fixes [nodegit.github.com issue #41](https://github.com/nodegit/nodegit.github.com/issues/41).
> Add @async tag to getEntry

- .travis.yml
- appveyor.yml
- package.json
v0.12 is breaking the deploy process now and v5 should be removed in favor of v7 which will come in a later commit.
> Remove Node v0.12 and v5

- generate/input/descriptor.json
- test/tests/branch.js
```
move
lookup
createFromAnnotated
```
Note that the test for `createFromAnnotated` is failing for me. It seems like the branch is being created even when the `force` flag has **not** been set. I would have expected the conflict in the branch's name to prevent the tag from being created but that's not happening.
The returned annotated commit does have the correct SHA-1 hash so that is not the issue. The branch that gets returned by the promise from `createFromAnnotated` has the same SHA-1 hash as what it was originally pointing at (ergo, the master commit) so it's almost as if the function call never happened! :thinking:
> Added tests for Branch

- .travis.yml
- appveyor.yml
- package.json
Testing out build support on Travis... built locally, but hitting weird error:
```
#
#
==== C stack trace ===============================
/usr/bin/node(v8::base::debug::StackTrace::StackTrace()+0x16) [0x106bda6]
/usr/bin/node(V8_Fatal+0xe8) [0x1069fe8]
/usr/bin/node(v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)+0xff) [0x76094f]
/home/tim/git/nodegit/nodegit/build/Release/nodegit.node(Wrapper::InitializeComponent(v8::Local<v8::Object>)+0x26d) [0x7fc0c190f58d]
/home/tim/git/nodegit/nodegit/build/Release/nodegit.node(init+0x43) [0x7fc0c190d8a3]
/usr/bin/node(node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)+0x365) [0xf51285]
/usr/bin/node(v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))+0x12f) …
```
> Node 7.4.0

- examples/merge-cleanly.js
This fixes #1128. The returned index is only in-memory and doesn't know where to write the .git/index file to so we should just skip the `write()` call and to just only use `writeTreeTo()` instead.
> Write the index to a repository directly in merge-cleanly.js examples

- lib/reset.js
According to libgit2's APIs, only git_commits and git_tags are acceptable. Update the documentation to accurately reflect this instead of just taking in an `Object`.
https://libgit2.github.com/libgit2/#HEAD/group/reset/git_reset
https://libgit2.github.com/libgit2/#HEAD/group/reset/git_reset_default
> Specify acceptable types for `lookup` and `dwim` in Reference

- generate/input/libgit2-supplement.json
- generate/templates/templates/binding.gyp
- generate/templates/templates/nodegit.js
- lib/clone.js
- lib/remote.js
- lib/submodule.js
- lib/utils/normalize_fetch_options.js
- vendor/libgit2.gyp
To get proxy support into NodeGit, we will need to get libgit configured to use libcurl. To start, we will just try to build nodegit against libcurl using the -lcurl flag.
We will also expose and handle proxy_options, the goal of this PR is to get proxy support in full across all systems.
This should address https://github.com/nodegit/nodegit/issues/489
> build against shared library for libcurl

- .gitignore
- generate/scripts/generateJson.js
- generate/scripts/generateMissingTests.js
- generate/scripts/generateNativeCode.js
- generate/scripts/utils.js
- package.json
The generation script now checks whether the file has changed before writing it to `/src` or `/include`. This is to improve compilation time when testing changes to generated code.
It works by creating a `/temp` directory, writing the generated code to `/temp/src` and `/temp/include`, then syncing those folders with `/src` and `/include` by deleting files  that no longer exist and copying files that have changed or been added since the last code generation. Finally the `/temp` directory is deleted
If `/src` and `/include` don't exist (i.e. it's the first time the generation script has been run), `/temp/src` will be copied to `/src` and `/temp/include` will be copied to `/include`.
> Generate script: Don't write .cc or .h files if unchanged

- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
- generate/templates/manual/include/convenient_hunk.h
- generate/templates/manual/include/convenient_patch.h
- generate/templates/manual/include/functions/copy.h
- generate/templates/manual/include/functions/free.h
- generate/templates/manual/include/git_buf_converter.h
- generate/templates/manual/include/str_array_converter.h
- generate/templates/manual/include/wrapper.h
- generate/templates/manual/remote/ls.cc
- generate/templates/manual/src/functions/copy.cc
- generate/templates/manual/src/functions/free.cc
- generate/templates/partials/async_function.cc
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/convert_to_v8.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/partials/fields.cc
- generate/templates/partials/sync_function.cc
- generate/templates/templates/binding.gyp
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/nodegit.cc
- generate/templates/templates/struct_content.cc
- generate/templates/templates/struct_header.h
- lib/remote.js
- test/tests/remote.js
Documentation for `git_remote_ls` shows that for it to work, a connection must be established to a remote first. When a subsequent connection is made, retrieved remote heads are destroyed and replaced with a new set.
This manual template locks the remote during execution of 3 actions (git_remote_connect, git_remote_ls, git_remote_disconnect) and copies all the data retrieved from git_remote_ls into memory for nodegit consumption.
The other contributing factor for using a manual template here is git_remote_ls has the only triple pointer use case in libgit2, so writing additional handlers for one case is overkill, especially when considering the volatility of the memory being retrieved. Complications that will exist if there is ever a good reason to build triple pointer handling into our …
> build safe convenience wrapper for git_remote_ls

- CONTRIBUTING.md
It seems like the maintainers of NodeGit are now in the Slack channel instead of Gitter so the `CONTRIBUTING.md` file should be updated accordingly.
> Replace references of Gitter with Slack in CONTRIBUTING.md

- generate/input/descriptor.json
- test/tests/revert.js
libgit2's `git_revert` function does not actually require the revert options to be specified. It is merely a [documentation oversight](https://github.com/libgit2/libgit2/pull/4108) on their website. We should flag the `given_opts` argument as being `isOptional` so that `null` can be passed into the JavaScript function.
> `RevertOptions` parameter in `Revert.revert` is actually optional

- generate/input/descriptor.json
- test/tests/stash.js
If you look at libgit2's [stash.h](https://github.com/libgit2/libgit2/blob/d02720d8a653bc564b84c27bfa01a6876bf5bec2/include/git2/stash.h#L59) file, you will see that the `message` parameter is actually optional. We should flag the argument as being optional in NodeGit's JSON file as well.
> String `message` argument of `Stash.save` is optional

- generate/templates/partials/convert_from_v8.cc
When compiling the C++ bridge code, you will see several warnings about the use of uninitialized variables.
**Linux / OSX**
```
../src/config.cc:376:2: warning: variable 'from_tx' is uninitialized when used here [-Wuninitialized]
*from_tx = Nan::ObjectWrap::Unwrap<GitTransaction>(info[0]->ToObject())->GetValue();
^~~~~~~
../src/config.cc:375:29: note: initialize the variable 'from_tx' to silence this warning
git_transaction ** from_tx;
^
= nullptr
```
**Windows**
```
nodegit\src\tree.cc(588): warning C4700: uninitialized local variable 'from_dest' used [nodegit\build\nodegit.vcxproj]
nodegit\src\rebase.cc(486): warning C4700: uninitialized local variable 'from_index' used [nodegit\build\nodegit.vcxproj]
nodegit\src\libgit2.cc(164): warning C4700: uninitialized local variable 'from_major' …
```
> Initialize pointers to fix compiler warnings about uninitialized local variables

- lib/repository.js
- test/tests/merge.js
When merging branches, we should provide a callback that allows users to inspect and modify the message that will be used for merging.
The generated merge message itself was also incorrect when compared to git core, and so has been updated to match git core.
> Update merge branches with processMergeMessageCallback

- generate/input/descriptor.json
- lib/reset.js
- test/tests/reset.js
The `fromAnnotated` function should be asynchronous in addition to having its `checkout_opts` parameter be optional as the function delegates to the same function as `reset` internally in libgit2.
> Make `Reset.fromAnnotated` the same as `Reset.reset`

- generate/templates/manual/include/callback_wrapper.h
Sufficiently large throttle values would cause an overflow - the cast coerces the computation into a sufficiently large int
> Use wider int to calculate throttle window

- lib/repository.js
- test/tests/rebase.js
When using the convenience methods for rebase, we should return all the details about the rebase before finishing. This includes the sha translation map for the rebase operation, and other meta data (old head sha, branch names, new head sha).
This is a breaking API change.
> Provide rebase details on finish

- lib/repository.js
- test/tests/signature.js
This domain is guaranteed to be unused (see RFC2606).  It is
inappropriate to use a real domain for a made-up email address.
> Use example.com domain for default signature.

- vendor/libgit2.gyp
We saw a big performance boost on git_diff_tree_to_tree in Windows 8 as a result of this change.
Also enabled the OpenSSL library to do hashing for OSX/Linux/BSD. We figured this would be better than using hash_generic as OpenSSL is more optimized.
> Hashing: use win32 bcrypt.dll, use openSSL on other platforms

- generate/input/descriptor.json
- test/tests/tree_entry.js
Fix #1268 by tweaking the generated code so that it doesn't take a pointer as a parameter.
> Expose a proper JavaScript API for TreeEntry's `toObject`

- .travis.yml
- appveyor.yml
> Add CI build config for node stable version

- generate/input/descriptor.json
- lib/repository.js
- test/tests/blob.js
- test/tests/diff.js
Exposed more blob methods from libgit2. The methods are:
- git_blob_filtered_content
- git_blob_create_fromdisk
Also made the createFromBuffer and createFromWorkdir methods asynchronous.
This is a breaking change to the blob api. createFromBuffer and createFromWorkdir are now asynchronous and thus return promises. This is because we try to maintain a standard of having methods that touch the disk as async to prevent deadlocks. While createFromBuffer does not touch the disk, it has a similar api to the other `createFrom*` methods and we thought it made sense to make it async.
> BREAKING: Added blob methods and converted to async

- generate/input/descriptor.json
- test/tests/tree_entry.js
- test/tests/treebuilder.js
git_tree_entry is marked as self freeing. But libgit2 only requires free'ing these in cases where the entry is retrieved from git_tree_entry_dup or git_tree_entry_bypath. Neither of which is exposed by nodegit.
This can lead to memory corruption and/or double free. This PR updates the default to make this not self freeing.
It also updates the treebuilder side to mark itself as the owner. The docs indicate https://libgit2.github.com/libgit2/#HEAD/group/treebuilder/git_treebuilder_insert that the returned tree_entry in a git_treebuilder_insert may not be valid past the next builder call. I couldn't find a way with the current generator to either fill this field in with NULL to not return the entry at all. Or duplicate it prior to returning.
> Fix git_tree_entry double free

- .travis.yml
- appveyor.yml
Last 8.3.0 build: https://ci.appveyor.com/project/TimBranyen/nodegit/build/3364
- this had a separate failure, but stable passed on this
First 8.4.0 build: https://ci.appveyor.com/project/TimBranyen/nodegit/build/3365
- all builds on windows stable after this build fail with the same error
We'll wait for an 8.4.1 patch release, and continue building for 8.3.0
> 8.4.0 currently breaks builds, locking to 8.3.0 temporarily

- generate/input/descriptor.json
- generate/templates/partials/async_function.cc
- generate/templates/partials/convert_to_v8.cc
- test/tests/filter.js
In GitBuf::Set and GitBuf::Grow the buffers could only accept a maximum buffer of 256MB because of limits with v8 string sizes. Removed the conversion to string in those methods to allow for larger buffers.
Also removed some special case logic in the async_functions template that would prevent proper buffer method generation, and then updated descriptors for methods that require proper buffer allocations to be "shouldAlloc": true
> Fixed an issue where large buffer allocations in filters (> 256MB) causes a segfault

- generate/input/callbacks.json
- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
Requires [libgit2 be bumped to the current master branch](https://github.com/nodegit/libgit2/pull/5) before this can be merged. These changes allow for the `git_push_update_reference_cb` to be generated in NodeGit, allowing for clients to determine if a remote ref rejected an update however still returned a valid response. An example would be when you push to a protected branch on GitHub.
> Updated input docs to allow for git_push_update_reference_cb to  generate

- generate/input/descriptor.json
- test/tests/index.js
`git_index_find` and `git_index_find_prefix` were not properly defined. Added definitions and tests for both routines, as well as made them asynchronous.
> Updated descriptors for git_index_find and git_index_find_prefix

- lib/revert.js
- test/tests/revert.js
If no options are specified for `Revert.revert`, the promise callback becomes the third parameter for the generated C++ revert.cc file and the (expected) fourth parameter as the promise callback will be unsatisfied which will lead to an exception. To fix this, we should generate a default options for the function instead of the callee doesn't provide one.
This fixes #1403.
> Generate default options for Revert.revert to prevent an exception

- generate/templates/templates/nodegit.js
- lib/revwalk.js
Discussion on why this change was required can be found in the following issues:
https://github.com/facebook/jest/issues/3552
https://github.com/facebook/jest/issues/3550
https://github.com/nodejs/node/issues/5016
> fix issue with re-require()'ing native modules

- generate/scripts/helpers.js
- generate/templates/manual/patches/convenient_patches.cc
- generate/templates/manual/remote/ls.cc
- generate/templates/manual/revwalk/fast_walk.cc
- generate/templates/manual/revwalk/file_history_walk.cc
- generate/templates/manual/src/filter_registry.cc
- generate/templates/partials/async_function.cc
- test/tests/merge.js
I've modified the `async_function.cc` template to include both the names of the JavaScript class and function in the error thrown in a rejected promise. This should hopefully make debugging NodeGit a lot easier when there's a long promise chain.
> Expose JavaScript function name in a rejected promise

- generate/templates/templates/binding.gyp
- vendor/openssl/openssl.gyp
Solves two issues:
1. clang does not support `-Wno-c++11-extensions`
2. nodegit uses c++11 and clang requires the `-std=c++11` flag to build with
Tested with clang-4, clang-5 and gcc-5.4
> Fix compiling with clang

- vendor/openssl/config/opensslconf.h
From upstream https://github.com/nodejs/node/pull/14313
Simplify the BSD list by defining OPENSSL_BSD if using a matching
BSD platform.
Add NetBSD to the list and update documentation.
PR-URL: #14313
Reviewed-By: Ben Noordhuis <info@bnoordhuis.nl>
Reviewed-By: James M Snell <jasnell@gmail.com>
> build: add NetBSD support to opensslconf.h

- examples/add-and-commit.js
A user reported in #1339 that an error will occur if you try to run the `examples/add-and-commit.js` example on Windows.
```
$ node add-and-commit.js
nodegit\node_modules\nodegit-promise\lib\done.js:10
throw err;
^
Error: invalid path: 'salad\toast\strangerinastrangeland\theresnowaythisexists\newfile.txt'
at Error (native)
```
This is because `addByPath` from of `Index` seems to only accept paths with forward slashes. Replacing the [`path.join`](https://github.com/nodegit/nodegit/blob/113493a9d3028a42ff30896ca32791835e8d68d9/examples/add-and-commit.js#L49) with `path.posix.join` will resolve the problem.
> Fix example by forcing backslashes with path.posix

- test/tests/annotated_commit.js
Introduce tests for the last two functions in `AnnotatedCommit` that aren't currently covered by the test suite.
`fromFetchhead`
`fromRevspec`
> Add tests for AnnotatedCommit

- examples/details-for-tree-entry.js
The example [currently](https://github.com/nodegit/nodegit/blob/df960879f76450dea738629e72bcbc990bea14c7/examples/details-for-tree-entry.js#L20-L23) calls functions on the `IndexEntry` object but those are actually fields so they should be accessed as such.
> Fix details-for-tree-entry.js to access fields instead of calling a function

- generate/input/descriptor.json
- test/tests/tag.js
The generated code for [`git_tag_peel()`](https://libgit2.github.com/libgit2/#v0.25.1/group/tag/git_tag_peel) is taking a pointer as a to return the peeled object. We should change the argument to be `isReturn` so that the generated API is sane from a JavaScript point of view.
> Add JavaScript version of `git_tag_peel()`

- lib/revwalk.js
Removed unnecessary annotation about return value.
Initial annotation was added in [ecf03e4216001e6844026770414f1e78cedf9dff]
> Fixed documentation error

- .travis.yml
- appveyor.yml
- package.json
* updated each minor Node.js version to the latest
* added Node.js 9
* https://travis-ci.org/inexorgame/nodegit/builds/346067294
* https://ci.appveyor.com/project/inexorgame/nodegit/build/4
* updates several deps to support more modern env setups (e.g. node-gyp 3.6.0 has fixes for VS2017)
> CI: Update Node.js versions + some deps

- lib/repository.js
- test/tests/rebase.js
Rebases currently expect the `rewritten` file to exist when a rebase occurs and a `beforeFinishFn` is specified. This is not the case when the rebase results in a fast-forward merge as nothing is rewritten.
> Handle fast-forward merges properly in repository.performRebase

- generate/input/descriptor.json
- test/tests/tag.js
I updated the descriptor file to add support for `git_tag_list_match`. This function was asked about on Slack.
> Add JavaScript Tag.listMatch function for git_tag_list_match

- generate/input/descriptor.json
- test/tests/status.js
```
Found non-matching argument named return in descriptor.json for C function git_status_file
```
The change I made for #1467 helped me discover an error in our wrapper for `git_status_file`. It seems like `Status.file` does not actually expose the C function's error code when an error occurs. I've fixed the descriptor and also added a test to hopefully ensure that this won't happen again in the future.
> Expose error code in Status.file

- .travis.yml
I didn't test the requested change to only deploy on tags well enough.
This led to the situation that the documentation is never getting deployed.
Cause of this: On tags the variable TRAVIS_BRANCH has the name of the tag. TRAVIS_BRANCH == master needs to get removed.
Also don't try to deploy nodegit binaries on extending testing and documentation deploy.
> Travis documentation deploy fixes

- generate/input/descriptor.json
- generate/input/libgit2-docs.json
- generate/input/libgit2-supplement.json
- generate/scripts/utils.js
- generate/templates/manual/commit/extract_signature.cc
- generate/templates/manual/patches/convenient_patches.cc
- generate/templates/manual/remote/ls.cc
- generate/templates/manual/revwalk/fast_walk.cc
- generate/templates/manual/revwalk/file_history_walk.cc
- generate/templates/manual/src/convenient_hunk.cc
- generate/templates/manual/src/convenient_patch.cc
- generate/templates/manual/src/filter_registry.cc
- generate/templates/manual/src/promise_completion.cc
- generate/templates/manual/src/wrapper.cc
- generate/templates/partials/async_function.cc
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/convert_from_v8.cc
- generate/templates/partials/field_accessors.cc
- package-lock.json
- package.json
- test/tests/diff.js
- test/tests/tag.js
- test/tests/treebuilder.js
- vendor/libgit2.gyp
- `NodeGit.Attr.prototype.get`
- `NodeGit.Blob.createFrombuffer`
- `NodeGit.Blob.createFromworkdir`
- `NodeGit.Reference.list`
- `NodeGit.Remote.prototype.getFetchRefspecs`
- `NodeGit.Remote.prototype.getPushRefspecs`
- `NodeGit.Attr.prototype.getMany`
- `NodeGit.Tag.prototype.target`
- `NodeGit.Treebuilder.prototype.Write`
- `add`
- `list`
- `lookup`
- `openFromRepository`
- `isLocked`
- `isPrunable`
- `lock`
- `prune`
- `unlock`
- `validate`
Diffs generated from `NodeGit.Diff.treeToIndex` and `NodeGit.Diff.treeToWorkdirWithIndex` conditionally support `NodeGit.Diff.OPTION.IGNORE_CASE`. Only on repositories where the index is case insensitive will the flag be set on the output diff. The flag itself is ignored when passed to DiffOptions.
> Bump to libgit2 v0.27.0

- test/tests/signature.js
The previous implementation mixed promises and callbacks in a way that was incompatible with mocha. This patch removes the callback and uses promises only. If the test failed, an "unhandled promise rejection warning" was emitted in recent Node.js versions.
> Fix asynchronous testing of signatures

- generate/input/descriptor.json
This change makes `ancestor_tree` and `opts` optional to match the documentation.
Closes: https://github.com/nodegit/nodegit/issues/1504
> Fix argument handling in Git.Merge.trees

- generate/input/descriptor.json
The `result` field for `git_ignore_path_is_ignored` and `git_tag_list_match` isn't being used so the compiler is generating warnings for the unused variable. I have fixed up `descriptor.json` so that they will be used.
```
../src/ignore.cc
:
192
:
7
:
warning
:
unused variable 'result' [-Wunused-variable]
int result = git_ignore_path_is_ignored(
^
CXX(target) Release/obj.target/nodegit/src/index_entry.o
1
warning
generated.
CXX(target) Release/obj.target/nodegit/src/index_time.o
CXX(target) Release/obj.target/nodegit/src/indexer.o
```
```
../src/tag.cc
:
1332
:
7
:
warning
:
unused variable 'result' [-Wunused-variable]
int result = git_tag_list_match(
^
4 warnings generated.
CXX(target) Release/obj.target/nodegit/src/time.o
CXX(target) Release/obj.target/nodegit/src/trace.o
```
> Define error codes to fix compiler warnings about unused variables

- .github/issue_template.md
Just asks for people to list their OS/arch/node/npm/yarn info when they're creating an issue since we get a lot of people omitting that, and even omitting the parts of the error logs that would expose that.
> add github issue template

- generate/input/callbacks.json
- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
- generate/scripts/helpers.js
- test/tests/remote.js
- test/utils/repository_setup.js
Have enabled the `pushTransferProgress` callback for `RemoteCallbacks`, which is used in `Remote.push`.
The [docs](http://www.nodegit.org/api/push_options/) for `PushOptions` says it accepts callbacks as `RemoteCallbacks` which is correct, but `transferProgress` is only for downloads, libgit has separate [API](https://libgit2.github.com/libgit2/#HEAD/type/git_remote_callbacks) for uploads.
I've been able to get the callback (`pushTransferProgress`) working, similar to `transferProgress` (with throttling). I just need help finishing it off.
**Current Issues**
Generate - The generate callback function uses a regex pattern (`/\s*_(cb|fn)/`) against the function name which isn't satisfied by libgit function name `git_push_transfer_progress`. For now, I've just put in a strict check to bypass. …
>  Enable git_push_transfer_progress - Help wanted

- examples/create-branch.js
The 'create-branch.js' example file had outdated params for 'Repository.createBranch() when compared to the API documentation. I changed the params to match the documentation.
> Fixed createBranch API params

- README.md
- generate/templates/templates/binding.gyp
- vendor/libgit2.gyp
On BSDs headers will be in /usr/local/include which
is not added to the include path automatically.
This is a rebased version of #1237 
Closes #1237
> Use curl-config to find curl

- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
- generate/templates/filters/fields_info.js
- generate/templates/filters/returns_info.js
- generate/templates/manual/clone/clone.cc
- generate/templates/manual/filter_list/load.cc
- generate/templates/manual/include/nodegit_wrapper.h
- generate/templates/manual/include/reference_counter.h
- generate/templates/manual/src/nodegit_wrapper.cc
- generate/templates/manual/src/reference_counter.cc
- generate/templates/partials/async_function.cc
- generate/templates/partials/convert_to_v8.cc
- generate/templates/partials/sync_function.cc
- generate/templates/partials/traits.h
- generate/templates/templates/binding.gyp
- generate/templates/templates/class_header.h
- generate/templates/templates/struct_header.h
- lib/clone.js
- lib/repository.js
- test/tests/annotated_commit.js
- test/tests/filter.js
- test/tests/patch.js
- test/tests/repository.js
So this is as much as I could glean.
Most objects that exist in the repository ODB or that extend from object are cached and reference counted. In order to ensure we are cleaning up memory for reference counted libgit2 objects, we should always call the provided libgit2 free method on the pointers when v8 garbage collects them. A lot of these reference counted objects have an underlying memory dependency with the repository, so the repository pointer will need to be kept around until the last call to the last object related to the repository has been freed. This means that most reference counted objects are owned by the repository. This class of objects will always call the free function, even if they have an owner.
Borrowed pointers are like fields on a struct. They should never be …
> Garbage collection: Free mostly everything automatically

- test/tests/repository.js
Surprisingly enough, `Repository`'s `getReferenceCommit` is not used anywhere in the tests.
> Add a test for Repository's getReferenceCommit

- lib/reset.js
- test/tests/reset.js
If a promise is passed down to the native C++ layer, v8 will crash. To ensure that this does not happen, a check will be performed in the JavaScript layer to verify that the repository is the same as the repository of the commit object.
While logically the commit of one repository instance is the same as a commit of another repository instance (if they point to the same `.git` folder), programmatically they are not equivalent as a check is done
on libgit2's side to ensure that they come from the same thing. As a result, the check on the JavaScript side purely compares the pointers over some other logical piece of information (such as its path or working directory).
This is not a general fix for #1127 but is simply meant to help the case of #1596. I have not put much thought into it but …
> Check parameters before performing reset

- generate/templates/templates/binding.gyp
Node should actually satisfy both of these links, because it actually exposes the headers for them. This isn't the case in Electron. This should hopefully solve some prebuilt issues regarding the various linuxes.
> Remove ssl and crypto dependency on non-electron builds

- lib/revert.js
- test/tests/revert.js
Seems we weren't normalizing mergeOpts correctly. Closes https://github.com/nodegit/nodegit/issues/1597
> Fix segfault in NodeGit.Revert.revert

- lib/repository.js
- test/tests/commit.js
This wraps the libgit commit signing methods.
~~I couldn't get to `git_commit_extract_signature` as it's not available until 0.24
https://libgit2.github.com/libgit2/#HEAD/group/commit/git_commit_extract_signature~~
> adds support for gpg commit signing (fixes #1018)

- lib/repository.js
It returns `Blob.createFromBuffer(...)` which calls [an async function](https://www.nodegit.org/api/blob/#createFromBuffer).
> Marked Repository.createBlobFromBuffer as async

- lib/commit.js
- lib/rebase.js
- lib/repository.js
- lib/tag.js
- test/tests/commit.js
- test/tests/rebase.js
- test/tests/tag.js
Any place where we implement a callback pattern for signing commits/tags follows the same API:
`type SigningCB = (content: string) => { code: number, field?: string, signedData?: string };`
What still needs to be done:
> Use same API for signingCb in all places that can be crypto signed

- generate/templates/templates/binding.gyp
- package-lock.json
- package.json
- utils/isBuildingForElectron.js
Since Electron is now at version >4, the iojs qualifier on the version number in the folder name for node headers stored in `~/.node-gyp` is no longer appended. This is because iojs and node merged at node v4. So that's the reason the <4 electron headers had iojs appended onto their header folder name. Now we need to support >4.
I tried messing about a bit with the exported config.gypi that is provided in the electron headers, but it doesn't seem to be included from the start :(. In lieu of going back to some sort of pangyp again, I've just parsed the config.gypi with json5 and am hoping for the best. We'll probably be back here in a year or 2 going, why? Why?!
> Handle new gyp information for electron builds

- generate/input/descriptor.json
- generate/templates/partials/sync_function.cc
- lib/reference.js
- lib/repository.js
- test/tests/checkout.js
- test/tests/commit.js
- test/tests/repository.js
- test/tests/signature.js
- test/tests/stash.js
- test/tests/tag.js
`Repository.prototype.createCommit` is able to handle updates to refs which do not exist because of the internal implementation of `git_commit_create` in libgit2. This PR exposes a reimplementation of this functionality so that `Repository.prototype.createCommitWithSignature` exhibits the same functionality.
> Fix non-existent / dangling refs cause Repository.prototype.createCommitWithSignature to fail

- lib/repository.js
- test/tests/rebase.js
This typo prevented the ability to skip commits where the patch was already applied. We will now treat the "patch already applied" error as an explicit "skip commit" action and ignore the error.
> Fix "errorno" typo

- generate/templates/templates/struct_content.cc
It looks like there might be another way to do this by specifying a trait on the persistent handle that specifies auto reset on destructor, but I couldn't find the trait.
> We should clear the persistent cell in structs when they are destroyed

- generate/input/callbacks.json
- generate/input/descriptor.json
- generate/input/libgit2-docs.json
- generate/input/libgit2-supplement.json
- lib/error.js
- lib/index.js
- lib/object.js
- lib/reference.js
- lib/remote.js
- test/tests/diff.js
Callbacks added:
- git_apply_delta_cb
- git_apply_hunk_cb
Methods added:
- git_annotated_commit_ref
- git_apply
- git_apply_to_tree
- git_merge_analysis
- git merge_analysis_for_ref
- git_remote_create_with_opts
Exposed classes:
- git_index_conflict_iterator
- git_index_iterator
> Update LibGit2 docs to v0.28.0

- generate/templates/templates/binding.gyp
- utils/isBuildingForIBMi.js
- vendor/libgit2.gyp
These changes allow nodegit to build in the IBM i operating system's PASE environment.
https://en.wikipedia.org/wiki/IBM_i
> Add support for building on IBM i (PASE)

- lib/rebase.js
It seems we expected that the signing CB would never throw or reject when returning a failure code. This PR should help alleviate unexpected behavior where throwing or rejecting should check for an error code and return that _or_ should return a generic -1 error.
> Catch errors and pass them to libgit2 as error codes in rebase signingcb

- generate/input/callbacks.json
- generate/input/libgit2-supplement.json
- generate/scripts/generateNativeCode.js
- generate/templates/filters/callback_args_count.js
- generate/templates/filters/callback_args_info.js
- generate/templates/filters/js_args_count.js
- generate/templates/manual/filter_source/repo.cc
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
- test/tests/filter.js
We don't have a very good pattern for garbage collection in callback parameters at the moment. After introducing garbage collection elsewhere in the library, we left callback parameters as not garbage collected, because they typically are owned by libgit2 anyway. So as long libgit2 is cleaning up their pointer, and we're cleaning up our v8 object, the memory ends up being cleaned up anyway.
The caveat was that callback parameters should not be trusted after a callback exits.
What sucks is that we discovered that you can access a git_repository from a git_filter_source, and that the git_repository that you can access is not guaranteed to be a git_repository that nodegit has ever seen before. In fact, it may not even be owned by NodeGit. In the case of submodules, when a …
> Clean up some dangerous memory accesses in callbacks

- generate/input/descriptor.json
- test/tests/repository.js
libgit2's [`git_repository_discover`](https://libgit2.github.com/libgit2/#v0.25.1/group/repository/git_repository_discover) function has an optional `ceiling_dirs` parameter. We should flag it as such in our JSON file.
> `ceiling_dirs` parameter in `Repository.discover` is optional

- .travis.yml
- appveyor.yml
Both Node 6 and Ubuntu 14.04 are EOL after April 2019. This PR removes support from those from CI.
> EOL for Node 6 and Ubuntu 14.04

- lib/commit.js
- test/tests/commit.js
Commit has functions that requires a reference to a repository to run. Because `parent(*)` was simply calling out to libgit2's `git_commit_parent` directly, its `repo` field was not being set.
Creating a wrapper in the `Commit` class and assigning a repository to the object before returning it will fix this problem.
Fixes #1653.
> Ensures that commits from parent(*) has a repository

- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
- generate/templates/manual/repository/get_references.cc
- generate/templates/manual/repository/get_remotes.cc
- generate/templates/manual/repository/get_submodules.cc
- generate/templates/manual/repository/refresh_references.cc
- generate/templates/manual/revwalk/commit_walk.cc
- lib/repository.js
- test/tests/remote.js
- test/tests/repository.js
Some getters are of particular concern to GitKraken, others have obvious utility to anyone getting many references or doing a commit walk.
This is breaking because `getRemotes` has been renamed to `getRemoteNames`, and now `getRemotes` returns remotes instead of strings.
> Add additional getters to streamline information gathering (breaking change)

- generate/templates/manual/repository/refresh_references.cc
Also removed calling `git_odb_free` when `git_repository_odb` fails.
This is a band-aid over a caching issue where LibGit2 is not checking the disk when listing the remote names. By manually reading the config, it busts whatever cache LibGit2 is holding on to.
> refresh_references.cc: bust LibGit2 remote list cache by reading config

- generate/input/descriptor.json
- generate/scripts/generateNativeCode.js
- generate/templates/filters/get_cpp_function_for_root_proto.js
- generate/templates/filters/has_function_on_root_proto.js
- generate/templates/templates/class_content.cc
Without treating the root of a nodegit collection as a function template when it is a function itself, when we do the importextension / fix the prototype dance, we were blowing away call, bind, and apply, as well as anything else on the prototype
> Root functions should keep their function prototypes correctly

- README.md
- generate/input/callbacks.json
- generate/input/descriptor.json
- generate/input/libgit2-docs.json
- generate/input/libgit2-supplement.json
- generate/scripts/helpers.js
- generate/templates/templates/binding.gyp
- vendor/libgit2.gyp
New library requirements:
**OSX**
- libiconv
- libgssapi-krb5
**Linux**
- libgssapi-krb5
- pcre
- pcreposix
On unix systems we now compile ntlmclient for ntlm support.
On Windows, we now compile pcre from libgit2 for regex support.
Hopefully this will get the ball rolling with 0.25.0 and get it out the door within a reasonable timeframe.
> Bump libgit2 to fork of latest master

- vendor/libgit2.gyp
CentOS 7 seems to segfault when built against its system PCRE library
> Use builtin regex library for linux for better portability

- generate/templates/templates/binding.gyp
There's no need to link to this library anymore.
> Remove pcre-config from binding.gyp

- vendor/libgit2.gyp
It seems that since we've been building without NSEC, if you operate on a repository that had been cloned without NSEC, using NSEC to perform working directory diffs can be incredibly slow. To mitigate massive slow downs, we'll turn this off for now. It can still be enabled and recompiled on a fork of NodeGit fairly easily.
> Remove NSEC

- generate/input/descriptor.json
- generate/templates/partials/convert_from_v8.cc
- test/tests/tree.js
Currently, `Tree#createUpdated` is not usable as new `TreeUpdate`s cannot be constructed and `createUpdated(repo, nupdates, updates)` only accepts a single `TreeUpdate` as `updates`.
This pull request allows to `new TreeUpdate()` and turns `updates` into an `Array<TreeUpdate>`.
Usage is, e.g., as follows:
```javascript
#!/usr/bin/env node
const Git = require("nodegit");
(async () => {
const repo = await Git.Repository.init("test", 1);
const odb = await repo.odb();
const emptyTree = await repo.getTree(await odb.write("", 0, Git.Object.TYPE.TREE));
const oid = await odb.write("test\n", 5, Git.Object.TYPE.BLOB);
const update = new Git.TreeUpdate();
update.action = Git.Tree.UPDATE.UPSERT;
update.filemode = Git.TreeEntry.FILEMODE.BLOB;
update.id = oid;
update.path = "directory1/file";
const …
```
> Make Tree#createUpdated usable

- generate/input/descriptor.json
Fixes: https://github.com/nodegit/nodegit/issues/1580
Note, this function should have been async as it reads from the disk. It will be async in the next version of NodeGit.
> Reintroduce Odb.prototype.addDiskAlternate

- lib/blame.js
Please correct me if I'm wrong, but I think the return type for the function `Blame.file` is missing in the documentation.
https://github.com/nodegit/nodegit/blob/af9e53f/lib/blame.js
https://www.nodegit.org/api/blame (25.07.2019)
> Add missing return type to Blame.file documentation

- generate/input/libgit2-supplement.json
- test/tests/rebase.js
In the current master there is missing the `RebaseOptions#inmemory` flag. This is why rebasing is currently not possible at all on bare repos. This fix adds the missing field in supplements config file. Rebasing works fine with `Rebase.init`.
> Fix rebase using in-memory index

- generate/input/descriptor.json
- generate/input/libgit2-docs.json
- generate/input/libgit2-supplement.json
- lib/blob.js
- test/tests/blob.js
Deprecates NodeGit.Blob.filteredContent and exposes NodeGit.Blob.prototype.filter
> Bump libgit2 to latest fork of master

- generate/input/libgit2-supplement.json
- generate/templates/manual/revwalk/commit_walk.cc
- generate/templates/templates/class_header.h
We do this exact routine in GitKraken every time we need to get commits from libgit2. Considering that `commit.getSignature` is async, we waste a ton of time in processing callbacks for our commits there. This will retrieve all of the data we need in bulk, and ship that back in a neater package.
> Optionally retrieve more data on commit walk

- lib/repository.js
`Repository#getCommit` uses `Commit.lookup` and then manually assigns to `Commit#repo` even though `Commit.lookup` already does that. There is no way for `Commit.lookup` to return a `Commit` without a `repo` property.
> Remove unnecessary assignment of Commit#repo

- lib/tree.js
- test/tests/diff.js
The `DiffList` is a legacy name for a type that doesn't currently exist. In cases where several diffs are returned, `Array<Diff>` is documented.
However, Tree#diff and Tree#diffWithOptions return a single `{Diff}`, which is incorrect in the docs:
- https://www.nodegit.org/api/tree/#diff
- https://www.nodegit.org/api/tree/#diffWithOptions
This PR removes `DiffList` from the repo to avoid confusion and updates to the correct type. Please see this previous issue for more context: https://github.com/nodegit/nodegit/issues/1359
Thanks for the library 👍
> Remove DiffList

- lib/commit.js
- test/tests/commit.js
`Commit#parent` did not assign the `repo` property so subsequent calls which relied on this property (such as `Commit#getTree`) failed. This change works around this problem by imitating what `LookupWrapper` does for `Commit.lookup`, that is, it wraps the actual call in a new function and manually assigns the `repo` property.
This commit also adds a test case for the corrected behavior.
> Fix behavior of Commit#parent

- package-lock.json
- package.json
- utils/acquireOpenSSL.js
- utils/discoverOpenSSLDistros.js
Request has now unmaintained, so we should switch to a newer and better package for fetching OpenSSL for Electron builds.
> Replace deprecated package request with got

- lib/remote.js
This was causing a segfault (sometimes) while pushing using connect/upload/disconnect. v8 was releasing the pointers to the options after the call to connect. When upload tries to reuse those pointers, they need to have survived until the remote is disconnected.
> Remote needs to persist the callback/proxyOpts/headers

- generate/templates/templates/binding.gyp
Fixes #1808
Apparently the C++ standard was dropped to C++11 fairly recently: https://github.com/nodegit/nodegit/commit/69d9d4e03235a52c13a5bd52d7a5f15aa0481655. This makes installation for Nodegit fail on Electron v11 (god knows why 😕).: 
<details>
<summary>NPM install output with Electron v11 on macOS 10.15.7</summary>
```
In file included from ../src/nodegit.cc:3:
In file included from /Users/leinelissen/Library/Caches/node-gyp/11.0.3/include/node/node.h:67:
In file included from /Users/leinelissen/Library/Caches/node-gyp/11.0.3/include/node/v8.h:30:
/Users/leinelissen/Library/Caches/node-gyp/11.0.3/include/node/v8-internal.h:418:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
!std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data); …
```
> Upgrade c++ standard to v14 to ensure compatibility with Electron v11

- generate/templates/manual/repository/refresh_references.cc
git_tag_message can return nullptr. From docs: "message of the tag or NULL when unspecified"
e.g. https://gitlab.freedesktop.org/mesa/mesa/-/tags/R300_DRIVER_0
> Don't strdup nullptr from git_tag_message 

- generate/templates/manual/include/context.h
- generate/templates/manual/src/context.cc
- generate/templates/manual/src/thread_pool.cc
- generate/templates/templates/nodegit.cc
If not, leak cleanup pointer like before.
Once the electron patch is in and released we can revert this.
https://github.com/electron/electron/issues/28043
> Check if module is compiled under context aware node version

- generate/input/descriptor.json
Simple PR. Just removing block for sideband_progress in remote_callbacks from generate/input/descriptor.json.
> Remove block for sideband_progress in remote_callbacks

- generate/templates/filters/returns_info.js
I'm preparing a PR for using eslint and prettier, and eslint pointed out this unused variable.
It looks like this was a mistake?
> returns_info: fix ownedByIndices

- lib/config.js
libgit2 expects an `int` as the value for `setBool` and returns an `int` for `getBool`.  We have booleans in JavaScript, so let's use them.
> Return/accept boolean for Config#get/setBool

- generate/templates/filters/args_info.js
- generate/templates/filters/fields_info.js
- generate/templates/manual/clone/clone.cc
- generate/templates/manual/commit/extract_signature.cc
- generate/templates/manual/filter_list/load.cc
- generate/templates/manual/filter_source/repo.cc
- generate/templates/manual/include/async_worker.h
- generate/templates/manual/include/convenient_hunk.h
- generate/templates/manual/include/convenient_patch.h
- generate/templates/manual/include/nodegit_wrapper.h
- generate/templates/manual/patches/convenient_patches.cc
- generate/templates/manual/remote/ls.cc
- generate/templates/manual/repository/get_references.cc
- generate/templates/manual/repository/get_remotes.cc
- generate/templates/manual/repository/get_submodules.cc
- generate/templates/manual/repository/refresh_references.cc
- generate/templates/manual/revwalk/commit_walk.cc
- generate/templates/manual/revwalk/fast_walk.cc
- generate/templates/manual/revwalk/file_history_walk.cc
- generate/templates/manual/src/async_worker.cc
- generate/templates/manual/src/convenient_hunk.cc
- generate/templates/manual/src/convenient_patch.cc
- generate/templates/manual/src/filter_registry.cc
- generate/templates/manual/src/nodegit_wrapper.cc
- generate/templates/partials/async_function.cc
- generate/templates/partials/field_accessors.cc
- test/tests/revwalk.js
We're seeing some super weird behavior where an object that was persisted is being cleaned up during async work. We need to workaround this issue, as we are reasonably certain that our persistent references are well formed. We suspect this is an issue with v8 itself rather than an issue with our code. We are now aggressively preventing GC from calling the objectwrap destructor until the objectwrap is no longer in use.
> Workaround: Prevent objectwrap from being cleaned up during async work

- generate/input/descriptor.json
- lib/patch.js
- test/tests/patch.js
According to the libgit2 documentation (https://libgit2.org/libgit2/#HEAD/group/patch/git_patch_from_blobs) all arguments are allowed to be NULL.
> Define optional arguments for Patch.fromBlobs()

- lib/rebase.js
- test/tests/rebase.js
Otherwise, we end up recursively calling signingCb every time Rebase.init or Rebase.open are called with the same options object
> Shallow clone rebase options before modifying

- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
- generate/templates/manual/include/worker_pool.h
- generate/templates/manual/repository/statistics.cc
- generate/templates/templates/class_header.h
- test/runner.js
- test/tests/repository.js
It returns same statistics as executing 'git-sizer -j' (https://github.com/github/git-sizer).
An example of the output of a test repository:
``` yaml
{
"repositorySize": {
"commits": {
"count": 992,
"size": 265544
},
"trees": {
"count": 2416,
"size": 1188325,
"entries": 32571
},
"blobs": {
"count": 4149,
"size": 48489622
},
"annotatedTags": {
"count": 1
},
"references": {
"count": 10
}
},
"biggestObjects": {
"commits": {
"maxSize": 956,
"maxParents": 2
},
"trees": {
"maxEntries": 93
},
"blobs": {
"maxSize": 1077756
}
},
"historyStructure": {
"maxDepth": 931,
"maxTagDepth": 1
},
"biggestCheckouts": {
"numDirectories": 128,
"maxPathDepth": 10,
"maxPathLength": 107,
"numFiles": 514,
"totalFileSize": 5160886,
"numSymlinks": 2,
"numSubmodules": 4
}
}
```
It counts all the repository's unique …
> Statistics with same output as "git-sizer -j"

- generate/templates/manual/include/thread_pool.h
- generate/templates/manual/src/async_baton.cc
- generate/templates/manual/src/thread_pool.cc
- test/tests/filter.js
- test/tests/submodule.js
- test/tests/worker.js
- test/utils/loop_checkout.js
- test/utils/worker_checkout.js
- test/utils/worker_context_aware.js
- test/utils/worker_context_aware_checkout.js
After a Threadpool rewrite for context-awareness, LFS checkouts started suffering long delays. We found the reason is that libgit2 callbacks that were being run in parallel started being run in sequence. But this is actually the safest way to deal with the callbacks, preventing deadlocks while being executed, and keeping the non-callback work thread-safe.
The changes here will just be an `UNSAFE` temporary workaround until LFS is properly integrated into NodeGit. The changes will be limited to the processing of callbacks from Workers that leverage threaded libgit2 functions (at the moment, only checkout functionality), and they basically allow the callbacks from the current Worker to be queued to the main JS thread without waiting for the current callback to end.
It is `UNSAFE` because …
> UNSAFE Temporary workaround for LFS checkout performance regression

- test/tests/clone.js
Since 15 March 2022 the unauthenticated git protocol on port 9418 is no longer supported in Github.
https://github.blog/2021-09-01-improving-git-protocol-security-github/
> Skip "can clone with git" test, unauthenticated git protocol is no longer supported in Github

- generate/templates/templates/binding.gyp
- guides/install/from-source/README.md
- utils/acquireOpenSSL.js
- utils/configureLibssh2.js
- vendor/libgit2.gyp
- vendor/patches/README.md
- vendor/patches/openssl/001-unix_force_getentropy_dso_lookup.patch
Several fixes included, they should be documented in the code.
Notable Changes:
- a code patching system
- only used to fix openssl old linux OS's(GLIBC <= 2.25) for now but can be expanded in the future if necessary
- openssl configure and build support for linux
- notably there is a flag passed here to hide all openssl symbols, without this, nodegit would segfault in cases where the electron environment has loaded in openssl
- Apparently we were building and shipping some node binaries without code in them, this was an artifact of making action-only targets but not declaring them as action-only. I fixed that.
- Also configured openssl on linux and mac to only build and install the headers and libs. we no longer build the additional apps, fuzzers, and docs. should result in a small speed …
> Statically compile OpenSSL on linux for electron

- generate/input/libgit2-supplement.json
E.g. `disabledFilters: ['nodegit_lfs']` to disable nodegit-lfs filters during checkout.
> Allow disabling specific filters during checkout

- vendor/libgit2.gyp
This will improve performance on LFS and big repos
We need this [PR7](https://github.com/nodegit/libgit2/pull/7) to avoid performance degradation.
> Enable GIT_USE_NSEC

- generate/input/libgit2-supplement.json
- generate/templates/manual/tree/get_all_filepaths.cc
- test/tests/tree.js
Getting all file paths from a big tree is a slow process.
This function will improve performance if only file paths from a tree are requested.
Performance times using a tree with about 73000 paths:
Using Tree.revwalk: from 7 to 8 seconds
Using Tree.getAllFilepaths: from 70 to 80 milliseconds
> Add getAllFilepaths function in tree object

- .github/workflows/tests.yml
10.15 is no longer supported by GitHub Actions
> Switch CI to macOS-11

- vendor/libssh2/src/agent.c
Free method_name
From this commit: [free method_name](https://github.com/libssh2/libssh2/pull/662/commits/b11d07dc2df92e0870c4e6457e2e05a3c1782e36)
Missed commit upgrading libssh2
> Fix leak in agent

- generate/templates/manual/src/convenient_hunk.cc
- generate/templates/manual/src/convenient_patch.cc
- generate/templates/manual/src/promise_completion.cc
- generate/templates/manual/src/wrapper.cc
- generate/templates/templates/binding.gyp
- generate/templates/templates/class_content.cc
- generate/templates/templates/struct_content.cc
- package-lock.json
- package.json
This was *not* fun to track down. Probably ~3 weeks of work?
This PR bumps nan to a custom version hosted on the axosoft org(could be moved to nodegit if necessary) and bumps the internal field count on object templates to account for the updates made to nan.
more details on what is happening and why, here:
https://github.com/Axosoft/nan/pull/1
and here:
https://github.com/electron/electron/blob/693cf0ebdebb272494610a5ed2e9c405e825813e/patches/node/be_compatible_with_cppgc.patch
> Fix intermittent crash on Electron 18+

- generate/templates/templates/binding.gyp
- utils/defaultCxxStandard.js
Electron 20+ requires C++17 but older node versions only require C++14
> Allow overriding C++ standard

- package-lock.json
- package.json
- test/tests/worker.js
bump nan to include this PR:
https://github.com/nodejs/nan/pull/956
which fixes building nan-based native modules for electron 28
> Fix electron 28 build failure

- generate/templates/manual/repository/get_references.cc
- generate/templates/manual/repository/get_remotes.cc
- lifecycleScripts/install.js
This fixes a crash that occurs on windows when trying to run `Repository.getReferences()` on a repo with refs that exceed the path-length limit in libgit2 more than once.
I don't know how else to trigger this issue so I can't really add a test for it.
> Don't free the given repo on error in getReferences and getRemotes

- generate/templates/manual/repository/get_references.cc
- generate/templates/manual/repository/get_remotes.cc
I didn't realize this beforehand but the `git_remote` object takes the pointer to the repo it's looked up on. Then when we construct a `GitRemote`, we create a wrapper around it's repo pointer which gets garbage collected later. I still don't see a good reason to duplicate the repo pointer and we don't in other cases of constructing `GitRemote` so I'm gonna remove it.
> Fix double-free introduced trying to fix other double-free

- generate/templates/templates/binding.gyp
necessary until node23 for building on newer versions of v8
> define NOMINMAX on windows
