- README.md
> Added debug build instructions.

- README.md
> Fixed a typo in the debug build instruction.

- appveyor.yml
- test/tests/clone.js
The clone tests are breaking appveyor and this PR is my attempt to figure out why since I can't consistently repo the test fails locally.
> [WIP] Attempt at fixing appveyor

- .gitignore
- generate/input/descriptor.json
- lib/commit.js
- test/tests/diff.js
New functions:
git_diff_tree_to_workdir
git_diff_tree_to_workdir_with_index
> [WIP] Added in some diff functions from libgit2

- package.json
Opened a PR to run this through CI before merging back in.
> Updated fs-extra to 0.15.0

- lifecycleScripts/clean.js
- lifecycleScripts/install.js
- package.json
Adds support for atom-shell to the automated build process.
> Atom shell support

- README.md
- package.json
After my changes to generation/build landed, the package scripts were out of date and needed tidying up.
> Fix the package scripts

- generate/input/descriptor.json
- lib/diff.js
- test/tests/diff.js
This adds support for `Diff.treeToIndex` and Diff.indexToWorkdir`
> Index diffing

- package.json
Just a few more being bumped up for good measure.
> One more dependency update

- README.md
Added @orderedlist to maintainers, added in badges table, and cleaned up
the "Build from source" section.
> Made changes to the README

- generate/input/descriptor.json
- lib/blob.js
- lib/checkout.js
- lib/clone.js
- lib/commit.js
- lib/index.js
- lib/merge.js
- lib/reference.js
- lib/remote.js
- lib/repository.js
- lib/revwalk.js
- lib/tag.js
- lib/tree.js
- lib/tree_entry.js
Make the docs better for the upcoming website generator.
> Update jsdoc and ignore some methods

- generate/templates/partials/field_accessors.cc
- test/tests/clone.js
A segfault was occuring when passing null values to `NanNew`, this patch
will the bug for `const char *` and `unsigned int` C types.  We'll
definitely need to add more in the future.
> Fixes segfault issue recorded in #406

- generate/input/callbacks.json
- generate/scripts/helpers.js
- generate/templates/filters/returns_info.js
- generate/templates/manual/src/str_array_converter.cc
- generate/templates/partials/async_function.cc
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/partials/sync_function.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/struct_content.cc
- lib/index.js
- package.json
- test/tests/clone.js
- test/tests/index.js
> Fix callbacks with just return value and single payload

- generate/input/descriptor.json
- generate/templates/templates/struct_content.cc
- lib/repository.js
- test/tests/index.js
Two semi-unrelated fixes, but hey... fixes.
> Fix indexEntry construction and blobFromBuffer

- .jshintrc
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
> Fix transfer callback stats

- generate/templates/filters/is_payload.js
- generate/templates/templates/struct_content.cc
> hide callback payloads from javascript

- generate/input/descriptor.json
- lib/remote.js
- test/tests/remote.js
This implements the descriptor, options normalization and unit test for pushing to a remote.
> Remote push

- generate/scripts/generateNativeCode.js
Just capture any errors on finding astyle and ignore them.
> supress astyle warnings

- generate/input/descriptor.json
- generate/templates/partials/field_accessors.cc
- test/tests/checkout.js
Pathspecs happen a ton in options structs, we can finally checkout individual 
files, etc.
I'll want some :eyes: on this to make sure the C++ isn't doing anything wrong or leaking somewhere.
> Adds support for strarray in structs

- examples/push.js
> Update push example

- generate/input/libgit2-supplement.json
- generate/scripts/generateJson.js
> Rename `Annotated` to `AnnotatedCommit`

- lifecycleScripts/install.js
- package.json
Regression introduced: https://github.com/nodegit/nodegit/commit/20ca86f1c027c39de4d0073e51597b0eda917134
> Revert node-pre-gyp to install not build

- generate/input/descriptor.json
- lib/index.js
- lib/repository.js
- package.json
- test/tests/index.js
- test/tests/packbuilder.js
- test/tests/pathspec.js
- test/tests/remote.js
- test/tests/repository.js
Also added in git_packbuilder_new -> Packbuilder.create.
> Converted create methods to be synchronous

- generate/templates/templates/nodegit.js
Hopefully this will give more accurate errors.
> Lots of complaints of missing build/Debug/nodegit

- generate/templates/templates/nodegit.js
- lib/convenient_hunk.js
- lib/convenient_line.js
- test/tests/diff.js
Also overrode the line content method to provide more useful results.
> Introduced a new ConvenientLine class to wrap the lines returned from ConvenientHunk.

- generate/input/descriptor.json
- test/tests/remote.js
> Make `Remote.delete` async and return error messages correctly

- lib/clone.js
- lib/utils/shallow_clone.js
Resolves https://github.com/nodegit/nodegit/issues/533
> Attempt remove the delete keyword

- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
- test/index.js
> This fixes polling sync promises in callbacks.

- generate/input/descriptor.json
- lib/diff.js
- test/tests/diff.js
Exposing this libgit2 API lets one diff the contents of a String against a file in the repository.
> A wrapper for git_diff_blob_to_buffer

- package.json
Lots of issues stemming from cleanup. Useful, so I've left the script, but it no longer runs automatically now.
> stop cleaning on post-install

- package.json
- test/tests/tree_entry.js
Fixes #565 
Waiting to merge until we can get the false positives resolved
> Fix build issues with 0.4.0

- test/tests/refs.js
I'm adding three test to fully cover lib/reference.js. Can you check that everything is alright?
> [test] Add tests to fully cover refs test

- test/tests/revparse.js
Another tests for good library. (:
I want to ask, if you would rather prefer small decoupled pull requests, or wait until there is more than N lines of code?
> Add test for RevParse object

- generate/templates/templates/nodegit.js
> if class has no functions, don't print it

- examples/diff-commits.js
> fix diff example

- lib/repository.js
Auto tag isn't just a number. It's an enum...
> Use `Remote.AUTOTAG_OPTION` enum for auto tag

- lib/convenient_hunk.js
- lib/convenient_patch.js
- lib/diff.js
- lib/tree.js
Docs weren't generating due to the array format.
nodegit/nodegit.github.com#31
> Fixing array return formatting in docs

- .travis.yml
- appveyor.yml
- package.json
Deploy shiz automatically when we push a tag!
> Autodeploy

- lib/convenient_patch.js
- `convenientPatch.isUnreadable`
- `convenientPatch.isConflicted`
> added missing isX (Diff.DELTA) functions to ConvenientPatch

- lib/repository.js
- test/tests/cherrypick.js
- test/tests/merge.js
- test/tests/rebase.js
Added repository convenience methods for checking repository state
> Repo state convenience functions

- lib/repository.js
Remake of https://github.com/nodegit/nodegit/pull/656 with lint fixes.
> only add filesToAdd -- not all

- lib/revwalk.js
Duplicate of https://github.com/nodegit/nodegit/pull/627
> Fix missing Revwalk#repo property

- README.md
Building from source instructions aren't on the readme!
> Link to building from source page

- lifecycleScripts/install.js
Fixes https://github.com/nodegit/nodegit/issues/710
> Use process.exitCode to indicate failure

- .travis.yml
- package.json
This is an experimental area to try and get our builds on the new container infrastructure with Travis-CI.
> Switch Travis CI to container infrastructure

- .gitignore
- test/index.js
- test/runner.js
- test/tests/config.js
Addresses https://github.com/nodegit/nodegit/issues/712
by setting HOME to some dummy directory.
> Set HOME environment variable for tests.

- lib/commit.js
- lib/tree.js
- test/tests/commit.js
Allows options for diffs so that we can do things like exclude whitespace for example.
> Added diff functions with options parameter.

- generate/templates/partials/async_function.cc
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/struct_content.cc
- generate/templates/templates/struct_header.h
- package.json
- test/tests/remote.js
callbacks don't return their rejection reason to the calling function, but only return a limited error.
> Fix callback rejections

- examples/push.js
See https://gitter.im/nodegit/nodegit?at=561c1b93773bc4af20ff1153
> Updated for the latest API changes 0.5.0

- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
- generate/scripts/generateJson.js
- generate/scripts/generateNativeCode.js
- generate/scripts/helpers.js
- generate/templates/manual/revwalk/fast_walk.cc
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
- test/tests/revwalk.js
This adds the manually written C++ function `fastWalk` the `RevWalk` class.
I also added in a system the let the developer add in optimized C++ code that will be added to
the library in a similar way that we wrap the libgit2 library. Basically, the developer just defines the 
API for the function to wrap and then just writes the C++ implementation of the functions. The
generator classes take care of the rest.
> Add `RevWalk.prototype.fastWalk`

- test/tests/cred.js
sshKeyFromAgent
usernameNew
hasUsername
> Added tests for {Cred}

- .travis.yml
- .travis/deploy-docs.sh
as suggested in #787
To make this work you will have to generate a GitHub API token with the `public_repo` permission and add it as a secret environment variable `GH_TOKEN` to the TravisCI project settings. After that every push to the `master` branch should automatically update the https://github.com/nodegit/nodegit.github.com repository.
> TravisCI: Automatically update "nodegit.github.com" repository

- generate/input/descriptor.json
- generate/scripts/helpers.js
- test/tests/branch.js
Dupe of #794 that seemed to have gotten lost?
> Make `Branch.setUpstream` and `Branch.upstream` async

- test/tests/annotated_commit.js
This doesn't cover all of the methods but it's a start
> AnnotatedCommit Tests

- lib/blame.js
- test/tests/blame.js
> Optional options for Blame.file

- generate/templates/manual/include/lock_master.h
- generate/templates/manual/include/nodegit.h
- generate/templates/manual/src/lock_master.cc
- generate/templates/partials/async_function.cc
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/partials/sync_function.cc
- generate/templates/templates/binding.gyp
- generate/templates/templates/class_content.cc
- generate/templates/templates/nodegit.cc
- generate/templates/templates/struct_content.cc
- test/tests/index.js
Prototype for a solution to https://github.com/nodegit/nodegit/issues/827
> Thread safety implementation using locking

- generate/input/descriptor.json
- test/tests/submodule.js
Adds support for `Submodule.status`, and makes a number of setters async to get better error handling, and match the behavior of the setters (writing to disk).
> Submodule get set

- generate/templates/manual/src/lock_master.cc
Maybe/hopefully fixes #869.
/cc @srajko
> Decrement the mutex use count after we've unlocked them.

- lib/repository.js
> Add `mergeOptions` to `Repository#mergeBranches`

- generate/templates/manual/src/lock_master.cc
- test/tests/thread_safety.js
Leaving the `uv_async` handle open was causing the node process to hang on exit.  Cleaning up mutexes on garbage collection achieves the same goal (mutexes will get cleaned up at some point, when they are no longer needed), and avoids the issue.
Using the GC is probably better performance-wise with thread safety enabled (mutex cleanup should be less frequent).  With thread-safety disabled, the mutex cleanup gets skipped (though for simplicity, the GC callback is configured throughout - I imagine this has minimal performance impact).
Fixes #866.
> Clean mutexes as part of garbage collection cycle instead of uv_async

- generate/templates/manual/revwalk/file_history_walk.cc
- lib/revwalk.js
- test/tests/revwalk.js
was dropping deleted events due to rename detection. oops.
> Hot fix historywalk

- lifecycleScripts/install.js
An extra whitespace killed the debug build. Because of course it did.
> Fix debug build

- generate/templates/manual/patches/convenient_patches.cc
- generate/templates/manual/src/convenient_patch.cc
Fixes #877.
It looks like #883 was supposed to fix this, but we missed the part where we actually did the free’ing. :see_no_evil: 
This is only WIP because I’m still trying to make a build so I can test that this fixes the whole problem.
> Let my patches go

- generate/scripts/generateNativeCode.js
- generate/scripts/utils.js
- generate/templates/templates/binding.gyp
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/nodegit.cc
- generate/templates/templates/struct_content.cc
- generate/templates/templates/struct_header.h
No more "this is a generated file" in non generated files
> tidy up comment generation

- .travis.yml
- appveyor.yml
- vendor/http_parser/.gitignore
- vendor/http_parser/AUTHORS
- vendor/http_parser/Makefile
- vendor/http_parser/README.md
- vendor/http_parser/contrib/url_parser.c
- vendor/http_parser/http_parser.c
- vendor/http_parser/http_parser.h
- vendor/http_parser/test.c
> Bump `http-parser` to v2.6.1

- test/tests/index.js
- test/utils/index_setup.js
The `createConflict` function in `test/utils/index_setup.js` was specialized for a specific index test. This PR generalizes it so it can be used in future tests.
> Tests: generalized createConflict in index utils

- generate/input/descriptor.json
- lib/repository.js
- test/tests/index.js
- test/tests/repository.js
- test/utils/index_setup.js
The test in this PR depends on #936
> Expose mergehead_foreach

- generate/input/callbacks.json
- generate/templates/manual/include/async_baton.h
- generate/templates/manual/include/callback_wrapper.h
- generate/templates/manual/include/lock_master.h
- generate/templates/partials/callback_helpers.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/templates/class_content.cc
- generate/templates/templates/class_header.h
- generate/templates/templates/struct_content.cc
- generate/templates/templates/struct_header.h
- test/tests/clone.js
A non-trivial number of segfaults are seeing this in production. Pulling this back for right now until a later release where we can fix them.
> Revert "Merge pull request #932 from srajko/callback-throttle"

- lib/diff.js
Update documentation to resolve https://github.com/nodegit/nodegit/issues/963
> Correct Diff.blobToBuffer documentation.

- examples/merge-cleanly.js
- examples/merge-with-conflicts.js
- examples/push.js
- examples/remove-and-commit.js
- generate/input/descriptor.json
- lib/repository.js
- test/tests/checkout.js
- test/tests/cherrypick.js
- test/tests/index.js
- test/tests/merge.js
- test/tests/rebase.js
- test/tests/repository.js
- test/tests/revwalk.js
- test/tests/stage.js
- test/utils/repository_setup.js
Anytime the index reads/writes to the disk it should be non-blocking. Additionally this will give us thread safety protection since async methods are piped through the `LockManager`
> Make index methods async

- generate/input/descriptor.json
Just a couple of fixes to descriptors that I wanted to submit separately.
> Descriptor fixes

- test/tests/diff.js
Kind of related to #1002. I'd like to eventually add a test where the diff options flags are not set to 1024 (IGNORE_CASE) but as of right now that test would fail. This is more to prove to myself that it is possible to merge a diff from a commit into a diff from the workdir and index and vice versa.
> Added more Diff.merge tests

- generate/input/libgit2-supplement.json
- test/tests/commit.js
Redoing https://github.com/nodegit/nodegit/pull/1009 so it can get merged in separately.
> Move reflog entry methods to ReflogEntry

- generate/input/descriptor.json
Adjusting `descriptor.json` to match change in 295f50703e6d995ff02de37f96c3ab91336e56b4
> Move git_tree_entry_free descriptor to tree_entry group

- generate/input/descriptor.json
- generate/scripts/helpers.js
- test/tests/commit.js
- test/tests/oid.js
- test/utils/leak_test.js
Redoing https://github.com/nodegit/nodegit/pull/1006 on top of https://github.com/nodegit/nodegit/pull/1014
> Oid leak fix

- generate/templates/manual/revwalk/fast_walk.cc
Thanks @srajko for holding my hand through this fix 👬
> Memory management: plugged leak in fastWalk

- examples/clone.js
- examples/general.js
- examples/read-file.js
In response to https://github.com/nodegit/nodegit/issues/1057#issuecomment-226798781
> changed references to entry.filename() to entry.name()

- guides/install/electron/README.md
- guides/install/nw.js/README.md
Should resolve https://github.com/nodegit/nodegit/issues/905, as well as comparable fixes for nw.js
> fix up electron and nw.js docs

- generate/input/descriptor.json
- test/tests/revwalk.js
Addresses leaks of GitRevwalk objects. Added a test and tested in GitKraken for stability.
> Fix revwalk memory leaks

- generate/input/descriptor.json
- generate/scripts/helpers.js
- test/tests/tree_entry.js
Addresses leaks of GitTreeEntry objects.  Added test, and tested in GitKraken for stability.
> Fix tree entry leaks

- vendor/libgit2.gyp
Fixes https://github.com/nodegit/nodegit/issues/1160
> FreeBSD also uses struct timespec st_mtim

- CHANGELOG.md
> Update 0.13 changelog

- test/tests/tag.js
> Added tests for Tag

- lifecycleScripts/configureLibssh2.js
This should fix the issue in https://github.com/nodegit/nodegit/issues/1082
> escape the spaces in dir for shell command

- lib/repository.js
> Update `Repository#createBranch` docs

- test/tests/commit.js
> Added tests for commit

- test/tests/refs.js
Added a test for renaming a ref
> Reference#rename test

- README.md
Add some info in the readme on how to resolve install problem about lifecycleScripts
> Add info about missing libssl-dev

- .travis.yml
- appveyor.yml
Removed CI Tool commands to test node version 4
> removed node v4 tests

- generate/input/callbacks.json
- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
- generate/scripts/generateJson.js
- generate/scripts/generateNativeCode.js
- generate/scripts/helpers.js
- generate/templates/filters/args_info.js
- generate/templates/filters/subtract.js
- generate/templates/filters/unsigned.js
- generate/templates/manual/include/async_baton.h
- generate/templates/manual/include/filter_registry.h
- generate/templates/manual/src/filter_registry.cc
- generate/templates/partials/async_function.cc
- generate/templates/partials/field_accessors.cc
- generate/templates/templates/binding.gyp
- generate/templates/templates/nodegit.cc
- generate/templates/templates/nodegit.js
- generate/templates/templates/struct_content.cc
- generate/templates/templates/struct_header.h
- lib/filter_registry.js
- test/tests/filter.js
Adding support for git_filter to nodegit.
Changes:
Filters are now asynchronous,
FilterRegistry added to register and unregister filters.
> Adding git_filter support in nodegit

- generate/input/descriptor.json
- generate/input/libgit2-docs.json
- lib/branch.js
- test/tests/branch.js
Exposed method for convenience in other packages
> Exposed libgit2 git_branch_remote_name method

- lib/blame.js
cf: https://github.com/nodegit/nodegit/blob/master/test/tests/blame.js#L32
> Annoate Blame.file as async

- test/tests/commit.js
I wrote a test for `lookupPrefix` and `nthGenAncestor`.
> Add two missing tests to Commit

- test/tests/tag.js
I've created a test for `targetId()` and `owner()`.
> Add two tests for Tag

- generate/input/descriptor.json
- test/tests/config.js
> Expose git_config functions

- examples/walk-history.js
http://www.nodegit.org/api/revwalk/#SORT
> Fix incorrect api usage, not Time rather TIME

- examples/checkout-remote-branch.js
- guides/cloning/README.md
- guides/cloning/gh-two-factor/README.md
- guides/cloning/ssh-with-agent/README.md
- lib/reference.js
- lib/repository.js
- lib/reset.js
Also, add the example requested in https://github.com/nodegit/nodegit/issues/1123.
> Improvements in documentation.

- README.md
https://github.com/nodegit/nodegit/issues/1490
> warn about node v10 incompatibility in readme

- lifecycleScripts/submodules/index.js
Experiencing issues with config locks on electron_npg_automator. This might potentially be the cause.
> Run submodule updates in sequence rather than parallel

- examples/add-and-commit.js
- examples/create-new-repo.js
- examples/general.js
- examples/merge-cleanly.js
- examples/merge-with-conflicts.js
- examples/push.js
- examples/remove-and-commit.js
Generally we do not specify the timestamp of commit, and  Signature.create is a bad case about using the param of time and offset in this example, we should not use 123456789, 987654321...
> More suitable example about Signature

- generate/templates/templates/binding.gyp
- utils/configureLibssh2.js
Fixes some lingering cruft from #1569
> Clean up libssh2 configure step

- lib/commit.js
- test/tests/commit.js
This change adds signing capabilities for amending commits.
> Add Commit#amendWithSignature

- generate/input/descriptor.json
- generate/input/libgit2-supplement.json
Exposes config methods:
- git_config_delete_entry
- git_config_delete_multivar
- git_config_get_bool
- git_config_get_int32
- git_config_get_int64
- git_config_set_multivar
- git_config_snapshot
Exposes git_config_iterator:
- git_config_iterator_new -> ConfigIterator.create
- git_config_iterator_glob_new -> ConfigIterator.createGlob
- git_config_multivar_iterator_new -> ConfigIterator.createMultivar
- git_config_next -> ConfigIterator.prototype.next
> Expose more config methods

- generate/templates/templates/binding.gyp
- utils/isBuildingForIBMi.js
- vendor/libgit2.gyp
Here are the simplifications requested on PR [#1634](https://github.com/nodegit/nodegit/pull/1634)
> Simplify check for IBM i operating system

- package-lock.json
Also includes a fix for security advisory in instanbul and a fix for rebase signing_cb not setting the git_error.
> Bump LibGit2 to fork of v0.28.1

- lifecycleScripts/preinstall.js
fixes https://github.com/nodegit/nodegit/issues/1593
> Don't fail yarn installs when we can't find npm

- package-lock.json
- package.json
#1661 Arbitrary File Overwrite vulnerability fixed
> Dependency upgrade node-gyp upgraded to 4.0.0

- generate/templates/manual/repository/refresh_references.cc
It's a bummer that this function completely dies just because of one corrupt ref. Instead of throwing an error on the entire function, let's instead skip mentioning the unresolvable ref.
> refresh_references.cc: skip refs that can't be directly resolved

- generate/input/descriptor.json
- generate/templates/partials/convert_from_v8.cc
- test/tests/tree.js
@rafaelgieschke created pull request #1254 some time ago. Unfortunately it has never been merged.
This pull request bases on his request and thus replaces it. I have merged and adapted Rafael's branch onto a fresh master as rebasing onto >500 commits lead to a too long sequence of conflicts.
It would be great to have this one merged, finally.
> Fix Tree#createUpdated 

- lib/repository.js
Closes #1707 and properly filters out references by type.
> Fix behaviour of Repository#getReferences

- generate/scripts/utils.js
I think this is responsible for the strange issue we're seeing where node generate fails to consistently install.
> Wait for copy and remove promises to finish

- vendor/libssh2/src/packet.c
https://github.com/libssh2/libssh2/pull/402
> Bring in libssh2#402

- lib/remote.js
https://github.com/nodegit/nodegit/issues/1764
> Dedupe Remote.prototype.fetch

- .github/workflows/tests.yml
MacOS -> 10.15
Retire Node 8
Build on Node 14
> Upgrade build environments

- .jshintrc
- examples/add-and-commit.js
- examples/create-new-repo.js
- examples/details-for-tree-entry.js
- examples/diff-commits.js
- examples/general.js
- examples/read-file.js
- package.json
The only non-syntactic changes are:
- used built-in `fs` instead of `fse` as the methods are there already
- fixed a few deprecation notices
Feedback welcome
> First stab at #1800 (async/await in examples)

- guides/install/from-source/README.md
- utils/acquireOpenSSL.js
> Allow download of prebuilt OpenSSL

- utils/acquireOpenSSL.js
- utils/build-openssl.bat
> Don't build shared OpenSSL libs

- generate/input/libgit2-supplement.json
- generate/templates/manual/patches/convenient_patches.cc
- lib/diff.js
Instead load all patches you can load the required patches in the array
> Improve Diff.patches to allow an index array

- .github/workflows/tests.yml
- generate/templates/templates/binding.gyp
- vendor/libgit2.gyp
Reverts nodegit/nodegit#1922
Firefox froze and I managed to click merge :upside_down_face: Let's try this again.
> Revert "Improve performance using LTO and disabling asserts"

- generate/input/descriptor.json
- generate/input/libgit2-docs.json
- generate/input/libgit2-supplement.json
- test/tests/stash.js
Bring in https://github.com/libgit2/libgit2/pull/6330
> Partial stash support

- lib/repository.js
> type is a call

- lib/tag.js
- test/tests/tag.js
Fix tag createWithSignature function
Also tests fixed
> Fix tag createWithSignature function

- package-lock.json
- package.json
> Update got + other locked package versions

- package-lock.json
- package.json
bump nan to include this PR:
https://github.com/nodejs/nan/pull/966
> Fix build failure on electron 29+

- package-lock.json
- package.json
bumped to include:
- https://github.com/nodejs/nan/pull/970
fixes #1999
> Bump nan again for electron 31

- .gitignore
- generate/templates/manual/repository/statistics.cc
- package-lock.json
- package.json
- utils/defaultCxxStandard.js
Add support for node 23 and electron 32+
> Bump @axosoft/nan and add ability to compile for c++20

- generate/templates/templates/binding.gyp
- package-lock.json
- package.json
- utils/acquireOpenSSL.mjs
- vendor/libgit2.gyp
- vendor/libssh2.gyp
fixes some vulnerabilities and minor build issues
> Dependency/Process Updates

- .github/workflows/tests.yml
- package-lock.json
- package.json
- utils/acquireOpenSSL.mjs
> Fix Invalid Import Assertion, Bump tar-fs
